// Code generated by protoc-gen-go.
// source: privet.proto
// DO NOT EDIT!

/*
Package privet is a generated protocol buffer package.

It is generated from these files:
	privet.proto

It has these top-level messages:
	Unit
	CommandResult
	PopUnitsRequest
	PopUnitsResponse
	ReportUnitsCompletionRequest
	ReportUnitsCompletionResponse
	QueueStatisticsRequest
	QueueStatisticsResponse
*/
package privet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Unit struct {
	Data                     string  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	ExpectedRuntimeInSeconds float64 `protobuf:"fixed64,2,opt,name=expected_runtime_in_seconds,json=expectedRuntimeInSeconds" json:"expected_runtime_in_seconds,omitempty"`
	Suite                    string  `protobuf:"bytes,3,opt,name=suite" json:"suite,omitempty"`
}

func (m *Unit) Reset()                    { *m = Unit{} }
func (m *Unit) String() string            { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()               {}
func (*Unit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CommandResult struct {
	ExitCode int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	Output   []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *CommandResult) Reset()                    { *m = CommandResult{} }
func (m *CommandResult) String() string            { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()               {}
func (*CommandResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PopUnitsRequest struct {
	RunnerId                          string  `protobuf:"bytes,1,opt,name=runner_id,json=runnerId" json:"runner_id,omitempty"`
	ApproximateBatchDurationInSeconds float64 `protobuf:"fixed64,2,opt,name=approximate_batch_duration_in_seconds,json=approximateBatchDurationInSeconds" json:"approximate_batch_duration_in_seconds,omitempty"`
}

func (m *PopUnitsRequest) Reset()                    { *m = PopUnitsRequest{} }
func (m *PopUnitsRequest) String() string            { return proto.CompactTextString(m) }
func (*PopUnitsRequest) ProtoMessage()               {}
func (*PopUnitsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PopUnitsResponse struct {
	Units []*Unit `protobuf:"bytes,1,rep,name=units" json:"units,omitempty"`
}

func (m *PopUnitsResponse) Reset()                    { *m = PopUnitsResponse{} }
func (m *PopUnitsResponse) String() string            { return proto.CompactTextString(m) }
func (*PopUnitsResponse) ProtoMessage()               {}
func (*PopUnitsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PopUnitsResponse) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

type ReportUnitsCompletionRequest struct {
	RunnerId                string         `protobuf:"bytes,1,opt,name=runner_id,json=runnerId" json:"runner_id,omitempty"`
	ResultId                string         `protobuf:"bytes,2,opt,name=result_id,json=resultId" json:"result_id,omitempty"`
	Units                   []*Unit        `protobuf:"bytes,3,rep,name=units" json:"units,omitempty"`
	UnitResult              *CommandResult `protobuf:"bytes,4,opt,name=unit_result,json=unitResult" json:"unit_result,omitempty"`
	AdditionalResultPresent bool           `protobuf:"varint,5,opt,name=additional_result_present,json=additionalResultPresent" json:"additional_result_present,omitempty"`
	AdditionalResult        *CommandResult `protobuf:"bytes,6,opt,name=additional_result,json=additionalResult" json:"additional_result,omitempty"`
}

func (m *ReportUnitsCompletionRequest) Reset()                    { *m = ReportUnitsCompletionRequest{} }
func (m *ReportUnitsCompletionRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportUnitsCompletionRequest) ProtoMessage()               {}
func (*ReportUnitsCompletionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReportUnitsCompletionRequest) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *ReportUnitsCompletionRequest) GetUnitResult() *CommandResult {
	if m != nil {
		return m.UnitResult
	}
	return nil
}

func (m *ReportUnitsCompletionRequest) GetAdditionalResult() *CommandResult {
	if m != nil {
		return m.AdditionalResult
	}
	return nil
}

type ReportUnitsCompletionResponse struct {
}

func (m *ReportUnitsCompletionResponse) Reset()                    { *m = ReportUnitsCompletionResponse{} }
func (m *ReportUnitsCompletionResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportUnitsCompletionResponse) ProtoMessage()               {}
func (*ReportUnitsCompletionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type QueueStatisticsRequest struct {
}

func (m *QueueStatisticsRequest) Reset()                    { *m = QueueStatisticsRequest{} }
func (m *QueueStatisticsRequest) String() string            { return proto.CompactTextString(m) }
func (*QueueStatisticsRequest) ProtoMessage()               {}
func (*QueueStatisticsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type QueueStatisticsResponse struct {
	UnitsInQueue    int32 `protobuf:"varint,1,opt,name=units_in_queue,json=unitsInQueue" json:"units_in_queue,omitempty"`
	UnitsInProgress int32 `protobuf:"varint,2,opt,name=units_in_progress,json=unitsInProgress" json:"units_in_progress,omitempty"`
}

func (m *QueueStatisticsResponse) Reset()                    { *m = QueueStatisticsResponse{} }
func (m *QueueStatisticsResponse) String() string            { return proto.CompactTextString(m) }
func (*QueueStatisticsResponse) ProtoMessage()               {}
func (*QueueStatisticsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Unit)(nil), "privet.Unit")
	proto.RegisterType((*CommandResult)(nil), "privet.CommandResult")
	proto.RegisterType((*PopUnitsRequest)(nil), "privet.PopUnitsRequest")
	proto.RegisterType((*PopUnitsResponse)(nil), "privet.PopUnitsResponse")
	proto.RegisterType((*ReportUnitsCompletionRequest)(nil), "privet.ReportUnitsCompletionRequest")
	proto.RegisterType((*ReportUnitsCompletionResponse)(nil), "privet.ReportUnitsCompletionResponse")
	proto.RegisterType((*QueueStatisticsRequest)(nil), "privet.QueueStatisticsRequest")
	proto.RegisterType((*QueueStatisticsResponse)(nil), "privet.QueueStatisticsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for JobMaster service

type JobMasterClient interface {
	PopUnits(ctx context.Context, in *PopUnitsRequest, opts ...grpc.CallOption) (*PopUnitsResponse, error)
	ReportUnitsCompletion(ctx context.Context, in *ReportUnitsCompletionRequest, opts ...grpc.CallOption) (*ReportUnitsCompletionResponse, error)
	GetQueueStatistics(ctx context.Context, in *QueueStatisticsRequest, opts ...grpc.CallOption) (*QueueStatisticsResponse, error)
}

type jobMasterClient struct {
	cc *grpc.ClientConn
}

func NewJobMasterClient(cc *grpc.ClientConn) JobMasterClient {
	return &jobMasterClient{cc}
}

func (c *jobMasterClient) PopUnits(ctx context.Context, in *PopUnitsRequest, opts ...grpc.CallOption) (*PopUnitsResponse, error) {
	out := new(PopUnitsResponse)
	err := grpc.Invoke(ctx, "/privet.JobMaster/PopUnits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobMasterClient) ReportUnitsCompletion(ctx context.Context, in *ReportUnitsCompletionRequest, opts ...grpc.CallOption) (*ReportUnitsCompletionResponse, error) {
	out := new(ReportUnitsCompletionResponse)
	err := grpc.Invoke(ctx, "/privet.JobMaster/ReportUnitsCompletion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobMasterClient) GetQueueStatistics(ctx context.Context, in *QueueStatisticsRequest, opts ...grpc.CallOption) (*QueueStatisticsResponse, error) {
	out := new(QueueStatisticsResponse)
	err := grpc.Invoke(ctx, "/privet.JobMaster/GetQueueStatistics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JobMaster service

type JobMasterServer interface {
	PopUnits(context.Context, *PopUnitsRequest) (*PopUnitsResponse, error)
	ReportUnitsCompletion(context.Context, *ReportUnitsCompletionRequest) (*ReportUnitsCompletionResponse, error)
	GetQueueStatistics(context.Context, *QueueStatisticsRequest) (*QueueStatisticsResponse, error)
}

func RegisterJobMasterServer(s *grpc.Server, srv JobMasterServer) {
	s.RegisterService(&_JobMaster_serviceDesc, srv)
}

func _JobMaster_PopUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobMasterServer).PopUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privet.JobMaster/PopUnits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobMasterServer).PopUnits(ctx, req.(*PopUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobMaster_ReportUnitsCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUnitsCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobMasterServer).ReportUnitsCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privet.JobMaster/ReportUnitsCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobMasterServer).ReportUnitsCompletion(ctx, req.(*ReportUnitsCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobMaster_GetQueueStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobMasterServer).GetQueueStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privet.JobMaster/GetQueueStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobMasterServer).GetQueueStatistics(ctx, req.(*QueueStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "privet.JobMaster",
	HandlerType: (*JobMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PopUnits",
			Handler:    _JobMaster_PopUnits_Handler,
		},
		{
			MethodName: "ReportUnitsCompletion",
			Handler:    _JobMaster_ReportUnitsCompletion_Handler,
		},
		{
			MethodName: "GetQueueStatistics",
			Handler:    _JobMaster_GetQueueStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("privet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x65, 0xf3, 0xa5, 0x64, 0x12, 0x68, 0x6b, 0xd1, 0x66, 0x49, 0x81, 0x86, 0x55, 0x2b, 0x45,
	0x1c, 0x7a, 0x08, 0x52, 0x0f, 0x48, 0x08, 0xa9, 0xa9, 0x84, 0x82, 0x84, 0x14, 0x5c, 0x21, 0x8e,
	0xab, 0x4d, 0x3c, 0x80, 0x45, 0x62, 0xbb, 0xb6, 0x17, 0xe5, 0xc8, 0x1f, 0xe0, 0xdf, 0xf0, 0x03,
	0x91, 0xbd, 0xde, 0x04, 0x92, 0xa6, 0xf4, 0xb6, 0x9e, 0xf7, 0xde, 0x8c, 0xe7, 0xf9, 0x69, 0xa1,
	0xa3, 0x34, 0xff, 0x81, 0xf6, 0x5c, 0x69, 0x69, 0x25, 0x69, 0x14, 0xa7, 0x44, 0x42, 0xed, 0x93,
	0xe0, 0x96, 0x10, 0xa8, 0xb1, 0xcc, 0x66, 0x71, 0xd4, 0x8f, 0x06, 0x2d, 0xea, 0xbf, 0xc9, 0x1b,
	0x38, 0xc6, 0xa5, 0xc2, 0x99, 0x45, 0x96, 0xea, 0x5c, 0x58, 0xbe, 0xc0, 0x94, 0x8b, 0xd4, 0xe0,
	0x4c, 0x0a, 0x66, 0xe2, 0x4a, 0x3f, 0x1a, 0x44, 0x34, 0x2e, 0x29, 0xb4, 0x60, 0x8c, 0xc5, 0x75,
	0x81, 0x93, 0xc7, 0x50, 0x37, 0x39, 0xb7, 0x18, 0x57, 0x7d, 0xcf, 0xe2, 0x90, 0x5c, 0xc1, 0xc3,
	0x91, 0x5c, 0x2c, 0x32, 0xc1, 0x28, 0x9a, 0x7c, 0x6e, 0xc9, 0x31, 0xb4, 0x70, 0xc9, 0x6d, 0x3a,
	0x93, 0x0c, 0xfd, 0xf8, 0x3a, 0x6d, 0xba, 0xc2, 0x48, 0x32, 0x24, 0x47, 0xd0, 0x90, 0xb9, 0x55,
	0xb9, 0xf5, 0xd3, 0x3a, 0x34, 0x9c, 0x92, 0x9f, 0x11, 0xec, 0x4d, 0xa4, 0x72, 0x57, 0x37, 0x14,
	0x6f, 0x72, 0x34, 0xbe, 0x91, 0xce, 0x85, 0x40, 0x9d, 0x72, 0x16, 0xf6, 0x68, 0x16, 0x85, 0x31,
	0x23, 0x13, 0x38, 0xcb, 0x94, 0xd2, 0x72, 0xc9, 0x17, 0x99, 0xc5, 0x74, 0x9a, 0xd9, 0xd9, 0xb7,
	0x94, 0xe5, 0x3a, 0xb3, 0x5c, 0x8a, 0xed, 0xad, 0x5e, 0xfc, 0x45, 0xbe, 0x74, 0xdc, 0xab, 0x40,
	0x5d, 0xad, 0x97, 0x5c, 0xc0, 0xfe, 0xfa, 0x06, 0x46, 0x49, 0x61, 0x90, 0x24, 0x50, 0xcf, 0x5d,
	0x21, 0x8e, 0xfa, 0xd5, 0x41, 0x7b, 0xd8, 0x39, 0x0f, 0x9e, 0x3b, 0x16, 0x2d, 0xa0, 0xe4, 0x77,
	0x05, 0x9e, 0x52, 0x54, 0x52, 0x5b, 0xaf, 0x1d, 0xc9, 0x85, 0x9a, 0xa3, 0x6b, 0x7d, 0xaf, 0x3d,
	0x1c, 0xe8, 0x7d, 0x73, 0x60, 0x25, 0x80, 0xbe, 0x30, 0x66, 0xeb, 0xf1, 0xd5, 0x9d, 0xe3, 0xc9,
	0x05, 0xb4, 0xdd, 0x47, 0x5a, 0x88, 0xe2, 0x5a, 0x3f, 0x1a, 0xb4, 0x87, 0x87, 0x25, 0xf3, 0x9f,
	0xa7, 0xa1, 0xe0, 0x98, 0xe1, 0x99, 0x5e, 0xc3, 0x93, 0x8c, 0x31, 0xee, 0x2e, 0x9a, 0xcd, 0x83,
	0x3a, 0x55, 0x1a, 0x0d, 0x0a, 0x1b, 0xd7, 0xfb, 0xd1, 0xa0, 0x49, 0xbb, 0x6b, 0x42, 0x21, 0x9a,
	0x14, 0x30, 0xb9, 0x84, 0x83, 0x2d, 0x6d, 0xdc, 0xb8, 0x6b, 0xf2, 0xfe, 0x66, 0xab, 0xe4, 0x04,
	0x9e, 0xed, 0x70, 0xad, 0xf0, 0x3e, 0x89, 0xe1, 0xe8, 0x63, 0x8e, 0x39, 0x5e, 0xdb, 0xcc, 0x72,
	0x63, 0xf9, 0xac, 0x0c, 0x46, 0xf2, 0x1d, 0xba, 0x5b, 0x48, 0x78, 0xb0, 0x53, 0x78, 0xe4, 0x6d,
	0x71, 0x09, 0xb8, 0x71, 0x9c, 0x90, 0xc0, 0x8e, 0xaf, 0x8e, 0x85, 0xd7, 0x91, 0x97, 0x70, 0xb0,
	0x62, 0x29, 0x2d, 0xbf, 0x6a, 0x34, 0x45, 0x50, 0xea, 0x74, 0x2f, 0x10, 0x27, 0xa1, 0x3c, 0xfc,
	0x55, 0x81, 0xd6, 0x7b, 0x39, 0xfd, 0x90, 0x19, 0x8b, 0x9a, 0xbc, 0x85, 0x66, 0x19, 0x12, 0xd2,
	0x2d, 0x57, 0xdd, 0x08, 0x6e, 0x2f, 0xde, 0x06, 0xc2, 0x4e, 0x0f, 0xc8, 0x17, 0x38, 0xbc, 0x75,
	0x6d, 0x72, 0x5a, 0x8a, 0xee, 0xca, 0x52, 0xef, 0xec, 0x3f, 0xac, 0xd5, 0x9c, 0xcf, 0x40, 0xde,
	0xa1, 0xdd, 0xb0, 0x89, 0x3c, 0x2f, 0xe5, 0xb7, 0x3b, 0xdb, 0x3b, 0xd9, 0x89, 0x97, 0x8d, 0xa7,
	0x0d, 0xff, 0xbf, 0x79, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x48, 0x22, 0xb8, 0x1f, 0x7f, 0x04,
	0x00, 0x00,
}
