// Code generated by protoc-gen-go.
// source: privet.proto
// DO NOT EDIT!

/*
Package privet is a generated protocol buffer package.

It is generated from these files:
	privet.proto

It has these top-level messages:
	Unit
	CommandResult
	PopUnitsRequest
	PopUnitsResponse
	ReportUnitsCompletionRequest
	ReportUnitsCompletionResponse
*/
package privet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Unit struct {
	Data                     string  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	ExpectedRuntimeInSeconds float64 `protobuf:"fixed64,2,opt,name=expected_runtime_in_seconds,json=expectedRuntimeInSeconds" json:"expected_runtime_in_seconds,omitempty"`
}

func (m *Unit) Reset()                    { *m = Unit{} }
func (m *Unit) String() string            { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()               {}
func (*Unit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CommandResult struct {
	ExitCode int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	Output   []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *CommandResult) Reset()                    { *m = CommandResult{} }
func (m *CommandResult) String() string            { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()               {}
func (*CommandResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PopUnitsRequest struct {
	RunnerId       string `protobuf:"bytes,1,opt,name=runner_id,json=runnerId" json:"runner_id,omitempty"`
	UnitsRequested int32  `protobuf:"varint,2,opt,name=units_requested,json=unitsRequested" json:"units_requested,omitempty"`
}

func (m *PopUnitsRequest) Reset()                    { *m = PopUnitsRequest{} }
func (m *PopUnitsRequest) String() string            { return proto.CompactTextString(m) }
func (*PopUnitsRequest) ProtoMessage()               {}
func (*PopUnitsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PopUnitsResponse struct {
	Units []*Unit `protobuf:"bytes,1,rep,name=units" json:"units,omitempty"`
}

func (m *PopUnitsResponse) Reset()                    { *m = PopUnitsResponse{} }
func (m *PopUnitsResponse) String() string            { return proto.CompactTextString(m) }
func (*PopUnitsResponse) ProtoMessage()               {}
func (*PopUnitsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PopUnitsResponse) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

type ReportUnitsCompletionRequest struct {
	RunnerId                string         `protobuf:"bytes,1,opt,name=runner_id,json=runnerId" json:"runner_id,omitempty"`
	ResultId                string         `protobuf:"bytes,2,opt,name=result_id,json=resultId" json:"result_id,omitempty"`
	Units                   []*Unit        `protobuf:"bytes,3,rep,name=units" json:"units,omitempty"`
	UnitResult              *CommandResult `protobuf:"bytes,4,opt,name=unit_result,json=unitResult" json:"unit_result,omitempty"`
	AdditionalResultPresent bool           `protobuf:"varint,5,opt,name=additional_result_present,json=additionalResultPresent" json:"additional_result_present,omitempty"`
	AdditionalResult        *CommandResult `protobuf:"bytes,6,opt,name=additional_result,json=additionalResult" json:"additional_result,omitempty"`
}

func (m *ReportUnitsCompletionRequest) Reset()                    { *m = ReportUnitsCompletionRequest{} }
func (m *ReportUnitsCompletionRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportUnitsCompletionRequest) ProtoMessage()               {}
func (*ReportUnitsCompletionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReportUnitsCompletionRequest) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *ReportUnitsCompletionRequest) GetUnitResult() *CommandResult {
	if m != nil {
		return m.UnitResult
	}
	return nil
}

func (m *ReportUnitsCompletionRequest) GetAdditionalResult() *CommandResult {
	if m != nil {
		return m.AdditionalResult
	}
	return nil
}

type ReportUnitsCompletionResponse struct {
}

func (m *ReportUnitsCompletionResponse) Reset()                    { *m = ReportUnitsCompletionResponse{} }
func (m *ReportUnitsCompletionResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportUnitsCompletionResponse) ProtoMessage()               {}
func (*ReportUnitsCompletionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Unit)(nil), "privet.Unit")
	proto.RegisterType((*CommandResult)(nil), "privet.CommandResult")
	proto.RegisterType((*PopUnitsRequest)(nil), "privet.PopUnitsRequest")
	proto.RegisterType((*PopUnitsResponse)(nil), "privet.PopUnitsResponse")
	proto.RegisterType((*ReportUnitsCompletionRequest)(nil), "privet.ReportUnitsCompletionRequest")
	proto.RegisterType((*ReportUnitsCompletionResponse)(nil), "privet.ReportUnitsCompletionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for JobMaster service

type JobMasterClient interface {
	PopUnits(ctx context.Context, in *PopUnitsRequest, opts ...grpc.CallOption) (*PopUnitsResponse, error)
	ReportUnitsCompletion(ctx context.Context, in *ReportUnitsCompletionRequest, opts ...grpc.CallOption) (*ReportUnitsCompletionResponse, error)
}

type jobMasterClient struct {
	cc *grpc.ClientConn
}

func NewJobMasterClient(cc *grpc.ClientConn) JobMasterClient {
	return &jobMasterClient{cc}
}

func (c *jobMasterClient) PopUnits(ctx context.Context, in *PopUnitsRequest, opts ...grpc.CallOption) (*PopUnitsResponse, error) {
	out := new(PopUnitsResponse)
	err := grpc.Invoke(ctx, "/privet.JobMaster/PopUnits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobMasterClient) ReportUnitsCompletion(ctx context.Context, in *ReportUnitsCompletionRequest, opts ...grpc.CallOption) (*ReportUnitsCompletionResponse, error) {
	out := new(ReportUnitsCompletionResponse)
	err := grpc.Invoke(ctx, "/privet.JobMaster/ReportUnitsCompletion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JobMaster service

type JobMasterServer interface {
	PopUnits(context.Context, *PopUnitsRequest) (*PopUnitsResponse, error)
	ReportUnitsCompletion(context.Context, *ReportUnitsCompletionRequest) (*ReportUnitsCompletionResponse, error)
}

func RegisterJobMasterServer(s *grpc.Server, srv JobMasterServer) {
	s.RegisterService(&_JobMaster_serviceDesc, srv)
}

func _JobMaster_PopUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobMasterServer).PopUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privet.JobMaster/PopUnits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobMasterServer).PopUnits(ctx, req.(*PopUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobMaster_ReportUnitsCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUnitsCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobMasterServer).ReportUnitsCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/privet.JobMaster/ReportUnitsCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobMasterServer).ReportUnitsCompletion(ctx, req.(*ReportUnitsCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "privet.JobMaster",
	HandlerType: (*JobMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PopUnits",
			Handler:    _JobMaster_PopUnits_Handler,
		},
		{
			MethodName: "ReportUnitsCompletion",
			Handler:    _JobMaster_ReportUnitsCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xdf, 0x8b, 0xd3, 0x30,
	0x1c, 0xb7, 0xbb, 0xb5, 0x74, 0xdf, 0x4d, 0xef, 0x0c, 0x9c, 0x57, 0xef, 0x14, 0x25, 0x28, 0xde,
	0xd3, 0x3d, 0x4c, 0xb8, 0x07, 0x41, 0x04, 0xe7, 0xcb, 0x04, 0x61, 0x44, 0x44, 0x7c, 0x0a, 0xdd,
	0xf2, 0x15, 0x02, 0x5b, 0x12, 0xdb, 0x54, 0xf6, 0x87, 0xed, 0x0f, 0x34, 0x3f, 0x5a, 0xa7, 0x9b,
	0x9b, 0xf7, 0xd4, 0x24, 0x9f, 0x5f, 0xdf, 0x7e, 0xd2, 0xc2, 0xc8, 0x54, 0xf2, 0x27, 0xda, 0x1b,
	0x53, 0x69, 0xab, 0x49, 0x16, 0x77, 0xf4, 0x1b, 0xf4, 0xbf, 0x28, 0x69, 0x09, 0x81, 0xbe, 0x28,
	0x6d, 0x59, 0x24, 0xcf, 0x93, 0xeb, 0x01, 0x0b, 0x6b, 0xf2, 0x16, 0xae, 0x70, 0x6d, 0x70, 0x61,
	0x51, 0xf0, 0xaa, 0x51, 0x56, 0xae, 0x90, 0x4b, 0xc5, 0x6b, 0x5c, 0x68, 0x25, 0xea, 0xa2, 0xe7,
	0xa8, 0x09, 0x2b, 0x3a, 0x0a, 0x8b, 0x8c, 0xa9, 0xfa, 0x1c, 0x71, 0xfa, 0x01, 0xee, 0x4f, 0xf4,
	0x6a, 0x55, 0x2a, 0xc1, 0xb0, 0x6e, 0x96, 0x96, 0x5c, 0xc1, 0x00, 0xd7, 0xd2, 0xf2, 0x85, 0x16,
	0x18, 0x82, 0x52, 0x96, 0xfb, 0x83, 0x89, 0xdb, 0x93, 0x47, 0x90, 0xe9, 0xc6, 0x9a, 0xc6, 0x06,
	0xdf, 0x11, 0x6b, 0x77, 0xf4, 0x2b, 0x9c, 0xce, 0xb4, 0xf1, 0x33, 0xd6, 0x0c, 0x7f, 0x34, 0x58,
	0x07, 0x1f, 0x37, 0x8e, 0xc2, 0x8a, 0x4b, 0xd1, 0x0e, 0x9c, 0xc7, 0x83, 0xa9, 0x20, 0xaf, 0xe0,
	0xb4, 0xf1, 0x64, 0x5e, 0x45, 0x36, 0x8a, 0x60, 0x98, 0xb2, 0x07, 0xcd, 0x1f, 0x1e, 0x28, 0xe8,
	0x2d, 0x9c, 0x6d, 0x8d, 0x6b, 0xa3, 0x55, 0x8d, 0x84, 0x42, 0x1a, 0x58, 0xce, 0xf5, 0xe4, 0x7a,
	0x38, 0x1e, 0xdd, 0xb4, 0x9d, 0x79, 0x16, 0x8b, 0x10, 0xdd, 0xf4, 0xe0, 0x09, 0x43, 0xa3, 0x2b,
	0x1b, 0xb4, 0xee, 0x15, 0xcd, 0x12, 0xad, 0xd4, 0xea, 0x4e, 0xe3, 0x79, 0x30, 0xb4, 0xe1, 0xc1,
	0x5e, 0x0b, 0x86, 0x03, 0x07, 0xfe, 0x8e, 0x3f, 0x39, 0x18, 0x4f, 0x6e, 0x61, 0xe8, 0x17, 0x3c,
	0x8a, 0x8a, 0xbe, 0xb3, 0x18, 0x8e, 0xcf, 0x3b, 0xe6, 0x5f, 0x85, 0x33, 0xf0, 0xcc, 0xb6, 0xfc,
	0x37, 0xf0, 0xb8, 0x14, 0x42, 0xfa, 0x41, 0xcb, 0x65, 0xab, 0xe6, 0xc6, 0x3d, 0x51, 0xd9, 0x22,
	0x75, 0x2e, 0x39, 0xbb, 0xd8, 0x12, 0xa2, 0x68, 0x16, 0x61, 0xf2, 0x1e, 0x1e, 0xee, 0x69, 0x8b,
	0xec, 0x58, 0xf2, 0xd9, 0xae, 0x15, 0x7d, 0x06, 0x4f, 0x0f, 0xb4, 0x16, 0xbb, 0x1f, 0x6f, 0x12,
	0x18, 0x7c, 0xd4, 0xf3, 0x4f, 0xa5, 0xbb, 0x9d, 0x8a, 0xbc, 0x83, 0xbc, 0xbb, 0x1d, 0x72, 0xd1,
	0x65, 0xec, 0x7c, 0x08, 0x97, 0xc5, 0x3e, 0x10, 0xcd, 0xe8, 0x3d, 0xf2, 0x1d, 0xce, 0xff, 0x99,
	0x47, 0x5e, 0x74, 0xa2, 0x63, 0x97, 0x78, 0xf9, 0xf2, 0x3f, 0xac, 0x2e, 0x67, 0x9e, 0x85, 0xff,
	0xe9, 0xf5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x7c, 0xd4, 0x58, 0x5f, 0x03, 0x00, 0x00,
}
