package main

import "github.com/sr/operator/generator"

var template = generator.NewTemplate("gen.go",
	`// Code generated by protoc-gen-bread. DO NOT EDIT.

package breadgen

import (
	"fmt"
	"errors"

	"github.com/sr/operator"
	"golang.org/x/net/context"
	"google.golang.org/grpc"

	"git.dev.pardot.com/Pardot/infrastructure/bread/chatbot"
{{range $k, $v := .Imports}}
	{{$k}} "{{$v}}"
{{end}}
)

func ChatCommandGRPCInvoker(ctx context.Context, conn *grpc.ClientConn, cmd *chatbot.Command) error {
	if conn == nil {
		return errors.New("required argument is nil: conn")
	}
	if cmd == nil {
		return errors.New("required argument is nil: cmd")
	}
	if cmd.Call == nil {
		return errors.New("required cmd struct field is nil: Call")
	}
{{- range .Services}}
{{if .Enabled }}
	{{- $pkg := .Package }}
	{{- $svc := .Name }}
	if cmd.Call.Package == "{{$pkg}}" && cmd.Call.Service == "{{$svc}}" {
	{{- range .Methods }}
		if cmd.Call.Method == "{{.Name}}" {
			_, err := {{$pkg}}.New{{$svc}}Client(conn).{{.Name}}(
				ctx,
				&{{$pkg}}.{{.Input}}{
					{{- range .Arguments}}
					{{inputField .Name}}: cmd.Args["{{.Name}}"],
					{{- end}}
				},
			)
			return err
		}
	{{- end }}
	}
{{- end }}
{{- end }}
	return fmt.Errorf("unhandleable command: %+v", cmd)
}

func OperatorInvoker(ctx context.Context, conn *grpc.ClientConn, req *operator.Request, pkg string) error {
{{- range .Services}}
{{if .Enabled }}
	{{- $pkg := .Package }}
	{{- $svc := .Name }}
	if req.Call.Service == fmt.Sprintf("%s.{{.Name}}", pkg) {
	{{- range .Methods }}
		if req.Call.Method == "{{.Name}}" {
			client := {{$pkg}}.New{{$svc}}Client(conn)
			_, err := client.{{.Name}}(
				ctx,
				&{{$pkg}}.{{.Input}}{
					Request: req,
					{{- range .Arguments}}
					{{inputField .Name}}: req.Call.Args["{{.Name}}"],
					{{- end}}
				},
			)
			return err
		}
	{{- end }}
	}
{{- end }}
{{- end }}
	return fmt.Errorf("no such service: `+"`"+"%s %s"+"`"+`", req.Call.Service, req.Call.Method)
}
`)
