ruby "2.3.1"

source "https://rubygems.org"

gem "active_model_serializers"
gem "audited", "4.3.0"
gem "bootstrap_form"
gem "coal_car", "~> 0.2.2"
gem "coffee-rails", "~> 4.1.0"
gem "faraday"
gem "fernet"
gem "font-awesome-rails"
gem "gemoji"
gem "github-markdown"
gem "html-pipeline"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "kaminari"
gem "librato-rails"
gem "local_time"
gem "nokogiri"
gem "octokit"
gem "omniauth-github"
gem "purple", path: "vendor/purple"
gem "puma", "2.15.3"
gem "pg"
gem "sass-rails", "~> 5.0"
gem "sidekiq-pro"
gem "rails", ">= 5.0.0.1", "< 5.1"
gem "rails-observers", "0.1.3.alpha"
gem "rinku"
gem "rollbar"
gem "tonitrus", "1.0.3"
gem "uglifier", ">= 1.3.0"

group :production do
  gem "rails_12factor"
end

group :development, :test do
  gem "dotenv-rails"
  gem "fabrication"
  gem "faker"
  gem "pry-byebug"
  gem "rspec-rails"
end

group :test do
  gem "capybara"
  gem "codeclimate-test-reporter", require: nil
  gem "launchy"
  gem "rubocop"
  gem "rspec", "3.5.0"
  gem "rspec-ontap"
  gem "webmock"
  gem "rails-controller-testing"
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "spring"
end
