package main

import "github.com/sr/operator/src/generator"

var template = generator.NewTemplate("main-gen.go",
	`// Code generated by protoc-gen-operatord
package main

import (
	"os"
	"fmt"
{{range .Services}}
	"{{.ImportPath}}"
{{end}}
	"google.golang.org/grpc"
	"github.com/sr/operator/src/operator"
	"go.pedge.io/env"
)

func run() error {
	config, err := operator.NewConfigFromEnv()
	if err != nil {
		return err
	}
	grpcServer := grpc.NewServer()
	logger := operator.NewLogger()
	instrumentator := operator.NewInstrumentator(logger)
	server := operator.NewServer(grpcServer, config, logger, instrumentator)
{{range .Services}}
	{{.Name}}Env := &{{.PackageName}}.Env{}
	if err := env.Populate({{.Name}}Env); err != nil {
		server.LogServiceStartupError("{{.Name}}", err)
	} else {
		if {{.Name}}Server, err := {{.PackageName}}.NewAPIServer({{.Name}}Env); err != nil {
			server.LogServiceStartupError("{{.Name}}", err)
		} else {
			instrumented := {{.PackageName}}.NewInstrumented{{camelCase .Name}}ServiceServer(instrumentator, {{.Name}}Server)
			{{.Name}}.Register{{camelCase .Name}}ServiceServer(grpcServer, instrumented)
		}
	}
{{end}}
	return server.Serve()
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "operatord: %s\n", err)
		os.Exit(1)
	}
}
`)
