source 'https://rubygems.org'
gem 'byebug', group: [:development, :test]
gem 'coffee-rails', '~> 4.0.0'
gem 'foreman', '0.78.0'
gem 'jquery-rails'
gem 'lograge', '0.3.6'
gem 'mysql2', '0.4.3'
gem 'omniauth', '1.3.1'
gem 'omniauth-ldap', '1.0.4'
gem 'puma', '2.15.3'
gem 'rails', '4.2.6'
gem 'sass-rails', '~> 4.0.3'
gem 'scrolls', '0.3.8'
gem 'sql-parser', github: "janSF/sql-parser"
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate'
