// Code generated by protoc-gen-operatord
package main

import (
	"errors"
	"flag"
	"os"
	"strings"

	"google.golang.org/grpc"

	bamboo "bread/bamboo"
	deploy "bread/deploy"
	pinger "bread/ping"
)

func buildOperatorServer(
	server *grpc.Server,
	flags *flag.FlagSet,
) (map[string]error, error) {
	bambooConfig := &bamboo.BambooConfig{}
	deployConfig := &deploy.DeployConfig{}
	pingerConfig := &pinger.PingerConfig{}
	flags.StringVar(&bambooConfig.BambooUsername, "bamboo-BambooUsername", "", "")
	flags.StringVar(&bambooConfig.BambooPassword, "bamboo-BambooPassword", "", "")
	flags.StringVar(&bambooConfig.BambooUrl, "bamboo-BambooUrl", "", "")
	flags.StringVar(&deployConfig.AwsRegion, "deploy-AwsRegion", "", "")
	flags.StringVar(&deployConfig.CanoeEcsService, "deploy-CanoeEcsService", "", "")
	flags.StringVar(&deployConfig.DeployTimeout, "deploy-DeployTimeout", "", "")
	services := make(map[string]error)
	if err := flags.Parse(os.Args[1:]); err != nil {
		return services, err
	}
	errs := make(map[string][]string)
	if bambooConfig.BambooUsername == "" {
		errs["bamboo"] = append(errs["bamboo"], "BambooUsername")
	}
	if bambooConfig.BambooPassword == "" {
		errs["bamboo"] = append(errs["bamboo"], "BambooPassword")
	}
	if bambooConfig.BambooUrl == "" {
		errs["bamboo"] = append(errs["bamboo"], "BambooUrl")
	}
	if deployConfig.AwsRegion == "" {
		errs["deploy"] = append(errs["deploy"], "AwsRegion")
	}
	if deployConfig.CanoeEcsService == "" {
		errs["deploy"] = append(errs["deploy"], "CanoeEcsService")
	}
	if deployConfig.DeployTimeout == "" {
		errs["deploy"] = append(errs["deploy"], "DeployTimeout")
	}
	if len(errs["ci"]) != 0 {
		services["ci"] = errors.New("required flag(s) missing: " + strings.Join(errs["ci"], ", "))
	} else {
		bambooServer, err := bamboo.NewAPIServer(bambooConfig)
		if err != nil {
			services["ci"] = err
		} else {
			bamboo.RegisterBambooServer(server, bambooServer)
			services["ci"] = nil
		}
	}
	if len(errs["deploy"]) != 0 {
		services["deploy"] = errors.New("required flag(s) missing: " + strings.Join(errs["deploy"], ", "))
	} else {
		deployServer, err := deploy.NewAPIServer(deployConfig)
		if err != nil {
			services["deploy"] = err
		} else {
			deploy.RegisterDeployServer(server, deployServer)
			services["deploy"] = nil
		}
	}
	if len(errs["pinger"]) != 0 {
		services["pinger"] = errors.New("required flag(s) missing: " + strings.Join(errs["pinger"], ", "))
	} else {
		pingerServer, err := pinger.NewAPIServer(pingerConfig)
		if err != nil {
			services["pinger"] = err
		} else {
			pinger.RegisterPingerServer(server, pingerServer)
			services["pinger"] = nil
		}
	}
	return services, nil
}
