// Code generated by protoc-gen-operatord
package main

import (
	"bread"
	"errors"
	"flag"
	"strings"

	"google.golang.org/grpc"

	ping "bread/ping"
)

func buildOperatorServer(
	server *grpc.Server,
	flags *flag.FlagSet,
	chatClient bread.ChatClient,
) (map[string]error, error) {
	pingConfig := &ping.PingerConfig{}
	services := make(map[string]error)
	errs := make(map[string][]string)
	if len(errs["ping"]) != 0 {
		services["ping"] = errors.New("required flag(s) missing: " + strings.Join(errs["ping"], ", "))
	} else {
		pingServer, err := ping.NewAPIServer(pingConfig, chatClient)
		if err != nil {
			services["ping"] = err
		} else {
			ping.RegisterPingerServer(server, pingServer)
			services["ping"] = nil
		}
	}
	return services, nil
}
