// Code generated by protoc-gen-operatord
package main

import (
	"github.com/sr/operator"
	"golang.org/x/net/context"
	"google.golang.org/grpc"

	ping "bread/ping"
)

func invoker(ctx context.Context, conn *grpc.ClientConn, req *operator.Request, args map[string]string) (bool, error) {
	if req.Call.Service == "ping" {
		if req.Call.Method == "otp" {
			client := ping.NewPingerClient(conn)
			_, err := client.Otp(
				ctx,
				&ping.OtpRequest{
					Request: req,
				},
			)
			if err != nil {
				return true, err
			}
			return true, nil
		}
		if req.Call.Method == "ping" {
			client := ping.NewPingerClient(conn)
			_, err := client.Ping(
				ctx,
				&ping.PingRequest{
					Request: req,
					Arg1:    args["arg1"],
				},
			)
			if err != nil {
				return true, err
			}
			return true, nil
		}
		if req.Call.Method == "whoami" {
			client := ping.NewPingerClient(conn)
			_, err := client.Whoami(
				ctx,
				&ping.WhoamiRequest{
					Request: req,
				},
			)
			if err != nil {
				return true, err
			}
			return true, nil
		}
	}
	return false, nil
}
