// Code generated by protoc-gen-operatord
package main

import (
	"time"

	"github.com/sr/grpcinstrument"
	"golang.org/x/net/context"

	servicepkg "services/papertrail"
)

type instrumented_papertrail_PapertrailService struct {
	instrumentator grpcinstrument.Instrumentator
	server         servicepkg.PapertrailServiceServer
}


// Search instruments the PapertrailService.Search method.
func (a *instrumented_papertrail_PapertrailService) Search(
	ctx context.Context,
	request *servicepkg.SearchRequest,
) (response *servicepkg.SearchResponse, err error) {
	defer func(start time.Time) {
		grpcinstrument.Instrument(
			a.instrumentator,
			"papertrail",
			"Search",
			"SearchRequest",
			"SearchResponse",
			err,
			start,
		)
	}(time.Now())
	return a.server.Search(ctx, request)
}
