// Code generated by protoc-gen-operatord
package main

import (
	"os"
	"fmt"

	"github.com/sr/operator"
	"google.golang.org/grpc"
	"go.pedge.io/env"


	"services/gcloud"

	"services/papertrail"

	"services/buildkite"

	"services/controller"

)

func run() error {
	config, err := operator.NewConfigFromEnv()
	if err != nil {
		return err
	}
	grpcServer := grpc.NewServer()
	logger := operator.NewLogger()
	instrumentator := operator.NewInstrumentor(logger)
	server := operator.NewServer(grpcServer, config, logger, instrumentator)

	gcloudEnv := &gcloud.Env{}
	if err := env.Populate(gcloudEnv); err != nil {
		operator.LogServiceStartupError("gcloud", err)
	} else {
		if gcloudServer, err := gcloud.NewAPIServer(gcloudEnv); err != nil {
			operator.LogServiceStartupError("gcloud", err)
		} else {
			instrumented := &instrumented_gcloud_GcloudService{instrumentator, gcloudServer}
			gcloud.RegisterGcloudServiceServer(grpcServer, instrumented)
			operator.LogServiceRegistered("gcloud")
		}
	}

	papertrailEnv := &papertrail.Env{}
	if err := env.Populate(papertrailEnv); err != nil {
		operator.LogServiceStartupError("papertrail", err)
	} else {
		if papertrailServer, err := papertrail.NewAPIServer(papertrailEnv); err != nil {
			operator.LogServiceStartupError("papertrail", err)
		} else {
			instrumented := &instrumented_papertrail_PapertrailService{instrumentator, papertrailServer}
			papertrail.RegisterPapertrailServiceServer(grpcServer, instrumented)
			operator.LogServiceRegistered("papertrail")
		}
	}

	buildkiteEnv := &buildkite.Env{}
	if err := env.Populate(buildkiteEnv); err != nil {
		operator.LogServiceStartupError("buildkite", err)
	} else {
		if buildkiteServer, err := buildkite.NewAPIServer(buildkiteEnv); err != nil {
			operator.LogServiceStartupError("buildkite", err)
		} else {
			instrumented := &instrumented_buildkite_BuildkiteService{instrumentator, buildkiteServer}
			buildkite.RegisterBuildkiteServiceServer(grpcServer, instrumented)
			operator.LogServiceRegistered("buildkite")
		}
	}

	controllerEnv := &controller.Env{}
	if err := env.Populate(controllerEnv); err != nil {
		operator.LogServiceStartupError("controller", err)
	} else {
		if controllerServer, err := controller.NewAPIServer(controllerEnv); err != nil {
			operator.LogServiceStartupError("controller", err)
		} else {
			instrumented := &instrumented_controller_Controller{instrumentator, controllerServer}
			controller.RegisterControllerServer(grpcServer, instrumented)
			operator.LogServiceRegistered("controller")
		}
	}

	return server.Serve()
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "operatord: %s\n", err)
		os.Exit(1)
	}
}
