FROM grpc/node:0.11
MAINTAINER me@simonrozet.com
RUN \
  apt-get install -y --no-install-recommends \
    build-essential \
    libicu-dev \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/cache
COPY /hubot/package.json /hubot/package.json
WORKDIR /hubot
RUN npm install
COPY /hubot/bin/hubot /hubot/bin/hubot
COPY /hubot/hubot-scripts.json /hubot/hubot-scripts.json
COPY /hubot/external-scripts.json /hubot/external-scripts.json
ENTRYPOINT ["bin/hubot"]
