#!/usr/bin/env bash
# Usage: script/test [--clean] [<test-file>]
# Run test suite for application. Optionallly pass in a path to an individual
# test file to run a single test.
set -euo pipefail

cd "$(dirname "$0")/.."

: "${CI:=""}"
: "${DEBUG:=""}"
[ -z "$DEBUG" ] || set -x

RACK_ENV="test"
RAILS_ENV="test"
RACK_ROOT=$(cd "$(dirname "$0")"/.. && pwd)
export RACK_ENV RAILS_ENV RACK_ROOT

script/setup

if test -n "$CI"
then script/vagrant-dev-mysqlimport --force
else script/vagrant-dev-mysqlimport
fi

echo "===> Running tests..."

if [ -n "${1:-""}" ]; then
  bin/rake test "$1"
else
  bin/rake
fi
