#!/usr/bin/env bash
# script/update: Update application to run for its current checkout.
set -eu

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating db..."
bin/rake db:create || true
bin/rake db:migrate
