#!/usr/bin/env bash
#/ Usage: vagrant-dev-mysqlimport [--force]
set -euo pipefail

cd "$(dirname "$0")/.."

: "${RAILS_ENV:="development"}"
: "${DATABASE_HOST:="localhost"}"
: "${DATABASE_PORT:="3306"}"

force=false
if [ "${1:-""}" = "--force" ]
then force=true
fi

if [ "$RAILS_ENV" != "development" ] && [ "$RAILS_ENV" != "test" ]
then
    echo "script/$(basename "$0") should never run in ${RAILS_ENV} environment"
    exit 1
fi

for dbname in pardot_global pardot_shard1 pardot_shard2
do
    dump="db/vagrant-dev/${dbname}.sql"

    if $force; then
        mysqladmin -u root -h "$DATABASE_HOST" -P "$DATABASE_PORT" \
            -f drop "$dbname" >/dev/null 2>&1 || true
        mysqladmin -u root -h "$DATABASE_HOST" -P "$DATABASE_PORT" \
            -f create "$dbname"
        echo "==> Importing $dump into database $dbname"
        mysql -u root -h "$DATABASE_HOST" -P "$DATABASE_PORT" "$dbname" < "$dump"
    else
        if mysqladmin -u root -h "$DATABASE_HOST" -P "$DATABASE_PORT" -f create "$dbname" >/dev/null 2>&1; then
            echo "==> Importing $dump into database $dbname"
            mysql -u root -h "$DATABASE_HOST" -P "$DATABASE_PORT" "$dbname" < "$dump"
        fi
    fi
done
