// Code generated by protoc-gen-go.
// source: papertrail/papertrail.proto
// DO NOT EDIT!

/*
Package papertrail is a generated protocol buffer package.

It is generated from these files:
	papertrail/papertrail.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	LogEvent
*/
package papertrail

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SearchRequest struct {
	Source *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Query  string           `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type SearchResponse struct {
	Output  *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
	Objects []*LogEvent      `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *SearchResponse) GetObjects() []*LogEvent {
	if m != nil {
		return m.Objects
	}
	return nil
}

type LogEvent struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Source     string `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Program    string `protobuf:"bytes,3,opt,name=program" json:"program,omitempty"`
	LogMessage string `protobuf:"bytes,4,opt,name=log_message,json=logMessage" json:"log_message,omitempty"`
}

func (m *LogEvent) Reset()                    { *m = LogEvent{} }
func (m *LogEvent) String() string            { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()               {}
func (*LogEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*SearchRequest)(nil), "papertrail.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "papertrail.SearchResponse")
	proto.RegisterType((*LogEvent)(nil), "papertrail.LogEvent")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for PapertrailService service

type PapertrailServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type papertrailServiceClient struct {
	cc *grpc.ClientConn
}

func NewPapertrailServiceClient(cc *grpc.ClientConn) PapertrailServiceClient {
	return &papertrailServiceClient{cc}
}

func (c *papertrailServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/papertrail.PapertrailService/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PapertrailService service

type PapertrailServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterPapertrailServiceServer(s *grpc.Server, srv PapertrailServiceServer) {
	s.RegisterService(&_PapertrailService_serviceDesc, srv)
}

func _PapertrailService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PapertrailServiceServer).Search(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _PapertrailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "papertrail.PapertrailService",
	HandlerType: (*PapertrailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _PapertrailService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x5b, 0x68, 0xe9, 0x56, 0x44, 0x60, 0x55, 0x28, 0x0d, 0x07, 0x50, 0x4e, 0x3d, 0x05,
	0xa9, 0x3c, 0x80, 0x13, 0x37, 0x50, 0x91, 0xf3, 0x00, 0xe4, 0xa6, 0xab, 0x90, 0xaa, 0xe9, 0x1a,
	0xdb, 0xa9, 0xc4, 0x95, 0x27, 0xf0, 0x62, 0x8c, 0x5d, 0xa7, 0x41, 0x70, 0x5b, 0xcf, 0xec, 0x8e,
	0x67, 0x76, 0xe1, 0x5a, 0x0a, 0x89, 0xca, 0x28, 0x51, 0x6d, 0xef, 0x8e, 0x65, 0x26, 0x15, 0x19,
	0x62, 0x70, 0x44, 0x92, 0x88, 0x6c, 0x29, 0x0c, 0x29, 0xcf, 0xa5, 0x4b, 0x38, 0xcf, 0x51, 0xa8,
	0xe2, 0x8d, 0xe3, 0x7b, 0x83, 0xda, 0xb0, 0x39, 0x0c, 0x35, 0x35, 0xaa, 0xc0, 0xb8, 0x77, 0xdb,
	0x9b, 0x4f, 0x16, 0x17, 0x59, 0x3b, 0x91, 0x3b, 0x9c, 0x1f, 0x78, 0x36, 0x85, 0x53, 0x3b, 0xa2,
	0x3e, 0xe2, 0xbe, 0x6d, 0x1c, 0x73, 0xff, 0x48, 0x37, 0x10, 0x05, 0x41, 0x2d, 0x69, 0xa7, 0xf1,
	0x47, 0x91, 0x1a, 0x23, 0x1b, 0xf3, 0x57, 0x71, 0xe9, 0x70, 0x7e, 0xe0, 0x59, 0x06, 0x23, 0x5a,
	0x6d, 0xb0, 0x30, 0xda, 0x6a, 0x0e, 0x6c, 0xeb, 0x34, 0xeb, 0x84, 0x79, 0xa2, 0xf2, 0x71, 0x8f,
	0x3b, 0xc3, 0x43, 0x53, 0x5a, 0xc3, 0x59, 0x00, 0x59, 0x04, 0xfd, 0x6a, 0xed, 0x7e, 0x18, 0x73,
	0x5b, 0xb1, 0xab, 0x36, 0x87, 0xb7, 0x17, 0x5c, 0xc7, 0x30, 0xb2, 0xc9, 0x4b, 0x25, 0xea, 0x78,
	0xe0, 0x88, 0xf0, 0x64, 0x37, 0x30, 0xd9, 0x52, 0xf9, 0x5a, 0xa3, 0xd6, 0xa2, 0xc4, 0xf8, 0xc4,
	0xb1, 0x60, 0xa1, 0x67, 0x8f, 0x2c, 0xd6, 0x70, 0xf9, 0xd2, 0xda, 0xc9, 0x51, 0xed, 0x2b, 0xab,
	0xf7, 0x00, 0x43, 0x9f, 0x97, 0xcd, 0xba, 0x66, 0x7f, 0x2d, 0x35, 0x49, 0xfe, 0xa3, 0xfc, 0x7a,
	0x92, 0xe8, 0xeb, 0x73, 0xd6, 0xb9, 0xd0, 0x6a, 0xe8, 0x0e, 0x73, 0xff, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xc9, 0xda, 0xce, 0xe9, 0xd3, 0x01, 0x00, 0x00,
}
