// Code generated by protoc-gen-go.
// source: papertrail/papertrail.proto
// DO NOT EDIT!

/*
Package papertrail is a generated protocol buffer package.

It is generated from these files:
	papertrail/papertrail.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	LogEvent
*/
package papertrail

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SearchRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SearchResponse struct {
	Events []*LogEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetEvents() []*LogEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type LogEvent struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Source     string `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Program    string `protobuf:"bytes,3,opt,name=program" json:"program,omitempty"`
	LogMessage string `protobuf:"bytes,4,opt,name=log_message" json:"log_message,omitempty"`
}

func (m *LogEvent) Reset()                    { *m = LogEvent{} }
func (m *LogEvent) String() string            { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()               {}
func (*LogEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*SearchRequest)(nil), "papertrail.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "papertrail.SearchResponse")
	proto.RegisterType((*LogEvent)(nil), "papertrail.LogEvent")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for PapertrailService service

type PapertrailServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type papertrailServiceClient struct {
	cc *grpc.ClientConn
}

func NewPapertrailServiceClient(cc *grpc.ClientConn) PapertrailServiceClient {
	return &papertrailServiceClient{cc}
}

func (c *papertrailServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/papertrail.PapertrailService/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PapertrailService service

type PapertrailServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterPapertrailServiceServer(s *grpc.Server, srv PapertrailServiceServer) {
	s.RegisterService(&_PapertrailService_serviceDesc, srv)
}

func _PapertrailService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PapertrailServiceServer).Search(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _PapertrailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "papertrail.PapertrailService",
	HandlerType: (*PapertrailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _PapertrailService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x48, 0x2c, 0x48,
	0x2d, 0x2a, 0x29, 0x4a, 0xcc, 0xcc, 0xd1, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xb8, 0x10, 0x22, 0x4a, 0x72, 0x5c, 0xbc, 0xc1, 0xa9, 0x89, 0x45, 0xc9, 0x19, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xbc, 0x5c, 0xac, 0x40, 0x46, 0x51, 0xa5, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0xa7, 0x92, 0x19, 0x17, 0x1f, 0x4c, 0xbe, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x85,
	0x8b, 0x2d, 0xb5, 0x2c, 0x35, 0xaf, 0xa4, 0x18, 0xa8, 0x82, 0x59, 0x83, 0xdb, 0x48, 0x44, 0x0f,
	0xc9, 0x02, 0x9f, 0xfc, 0x74, 0x57, 0x90, 0xa4, 0x92, 0x0f, 0x17, 0x07, 0x8c, 0x2d, 0xc4, 0xc5,
	0xc5, 0x94, 0x99, 0x02, 0x31, 0x4f, 0x88, 0x8f, 0x8b, 0xad, 0x38, 0xbf, 0xb4, 0x28, 0x39, 0x55,
	0x82, 0x09, 0xcc, 0xe7, 0xe7, 0x62, 0x07, 0x3a, 0x2a, 0xbd, 0x28, 0x31, 0x57, 0x82, 0x19, 0x2c,
	0x20, 0xcc, 0xc5, 0x9d, 0x93, 0x9f, 0x1e, 0x9f, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0xc1,
	0x02, 0x12, 0x34, 0x0a, 0xe1, 0x12, 0x0c, 0x80, 0x5b, 0x12, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c,
	0x2a, 0x64, 0xcf, 0xc5, 0x06, 0x71, 0x9a, 0x90, 0x24, 0xb2, 0x13, 0x50, 0xbc, 0x23, 0x25, 0x85,
	0x4d, 0x0a, 0xe2, 0x93, 0x24, 0x36, 0x70, 0x70, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0d,
	0x4e, 0xa5, 0x6f, 0x2d, 0x01, 0x00, 0x00,
}
