#!/usr/bin/env bash

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating db..."
# run all database migrations to ensure everything is up to date.
bin/rake db:create || true
bin/rake db:migrate

echo "===> Creating projects"
bin/rake canoe:create_projects
echo "===> Creating development targets"
bin/rake canoe:create_targets
echo "===> Creating deploy ACLs"
bin/rake canoe:create_deploy_acls
