#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

: "${HAL9000_ENV:="development"}"
export HAL9000_ENV

PATH="$(pwd)/bin:$PATH"
export PATH

RUBYLIB="$(pwd)/lib:${RUBYLIB:-""}"
export RUBYLIB

bin/hal9000
