# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hal/hal9000.proto

require 'google/protobuf'

require 'google/protobuf/empty'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hal.Message" do
    optional :text, :string, 1
  end
  add_message "hal.IsMatchResponse" do
    optional :match, :bool, 1
  end
end

module Hal
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("hal.Message").msgclass
  IsMatchResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("hal.IsMatchResponse").msgclass
end
