// Code generated by protoc-gen-go.
// source: gcloud/gcloud.proto
// DO NOT EDIT!

/*
Package gcloud is a generated protocol buffer package.

It is generated from these files:
	gcloud/gcloud.proto

It has these top-level messages:
	Instance
	Operation
	ListInstancesRequest
	ListInstancesResponse
	ListOperationsRequest
	ListOperationsResponse
*/
package gcloud

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/sr/operator/src/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Instance struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Zone   string `protobuf:"bytes,4,opt,name=zone" json:"zone,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Operation struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListInstancesRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id" json:"project_id,omitempty"`
}

func (m *ListInstancesRequest) Reset()                    { *m = ListInstancesRequest{} }
func (m *ListInstancesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListInstancesRequest) ProtoMessage()               {}
func (*ListInstancesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListInstancesResponse struct {
	Output  *proto1.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
	Objects []*Instance    `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
}

func (m *ListInstancesResponse) Reset()                    { *m = ListInstancesResponse{} }
func (m *ListInstancesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListInstancesResponse) ProtoMessage()               {}
func (*ListInstancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListInstancesResponse) GetOutput() *proto1.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ListInstancesResponse) GetObjects() []*Instance {
	if m != nil {
		return m.Objects
	}
	return nil
}

type ListOperationsRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id" json:"project_id,omitempty"`
}

func (m *ListOperationsRequest) Reset()                    { *m = ListOperationsRequest{} }
func (m *ListOperationsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOperationsRequest) ProtoMessage()               {}
func (*ListOperationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListOperationsResponse struct {
	Operations []*Operation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
}

func (m *ListOperationsResponse) Reset()                    { *m = ListOperationsResponse{} }
func (m *ListOperationsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListOperationsResponse) ProtoMessage()               {}
func (*ListOperationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListOperationsResponse) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func init() {
	proto.RegisterType((*Instance)(nil), "gcloud.Instance")
	proto.RegisterType((*Operation)(nil), "gcloud.Operation")
	proto.RegisterType((*ListInstancesRequest)(nil), "gcloud.ListInstancesRequest")
	proto.RegisterType((*ListInstancesResponse)(nil), "gcloud.ListInstancesResponse")
	proto.RegisterType((*ListOperationsRequest)(nil), "gcloud.ListOperationsRequest")
	proto.RegisterType((*ListOperationsResponse)(nil), "gcloud.ListOperationsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for GCloudService service

type GCloudServiceClient interface {
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error)
}

type gCloudServiceClient struct {
	cc *grpc.ClientConn
}

func NewGCloudServiceClient(cc *grpc.ClientConn) GCloudServiceClient {
	return &gCloudServiceClient{cc}
}

func (c *gCloudServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	out := new(ListInstancesResponse)
	err := grpc.Invoke(ctx, "/gcloud.GCloudService/ListInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gCloudServiceClient) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error) {
	out := new(ListOperationsResponse)
	err := grpc.Invoke(ctx, "/gcloud.GCloudService/ListOperations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GCloudService service

type GCloudServiceServer interface {
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error)
}

func RegisterGCloudServiceServer(s *grpc.Server, srv GCloudServiceServer) {
	s.RegisterService(&_GCloudService_serviceDesc, srv)
}

func _GCloudService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GCloudServiceServer).ListInstances(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GCloudService_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GCloudServiceServer).ListOperations(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _GCloudService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcloud.GCloudService",
	HandlerType: (*GCloudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstances",
			Handler:    _GCloudService_ListInstances_Handler,
		},
		{
			MethodName: "ListOperations",
			Handler:    _GCloudService_ListOperations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0x5b, 0xf2, 0xff, 0x77, 0x34, 0x45, 0xd7, 0x2a, 0x21, 0x58, 0xd1, 0x80, 0x20,
	0x0a, 0x29, 0x54, 0x3c, 0x0b, 0x7a, 0x10, 0xa1, 0x10, 0xd0, 0x93, 0x27, 0x49, 0xd3, 0x45, 0x22,
	0xba, 0x13, 0xb3, 0x13, 0x41, 0x3f, 0x94, 0x9f, 0xd1, 0xcd, 0x6e, 0x36, 0x90, 0x68, 0x3c, 0x2d,
	0x33, 0xef, 0xed, 0x6f, 0xde, 0x0c, 0xec, 0x3c, 0xa5, 0x2f, 0x58, 0xae, 0xe7, 0xe6, 0x89, 0xf2,
	0x02, 0x09, 0x99, 0x6b, 0xaa, 0x60, 0xaa, 0xcb, 0x39, 0xe6, 0xbc, 0x48, 0x08, 0x0b, 0xa3, 0x86,
	0x57, 0xf0, 0xff, 0x56, 0x48, 0x4a, 0x44, 0xca, 0x19, 0xc0, 0x20, 0x5b, 0xfb, 0xce, 0xa1, 0x73,
	0x32, 0x66, 0x9b, 0x30, 0x12, 0xc9, 0x2b, 0xf7, 0x07, 0xba, 0x9a, 0x80, 0xab, 0x3c, 0x54, 0x4a,
	0x7f, 0x68, 0xd5, 0x4f, 0x14, 0xdc, 0x1f, 0x55, 0x55, 0x78, 0x01, 0xe3, 0x58, 0x53, 0x33, 0x14,
	0x5d, 0x08, 0x7d, 0xe4, 0x3d, 0x90, 0xf0, 0x14, 0xa6, 0xcb, 0x4c, 0x92, 0x1d, 0x2f, 0xef, 0xf8,
	0x5b, 0xc9, 0x25, 0x31, 0x85, 0x50, 0xd9, 0x9e, 0x79, 0x4a, 0x8f, 0x96, 0x14, 0x3e, 0xc0, 0x6e,
	0xc7, 0x2b, 0x73, 0x14, 0x92, 0xb3, 0x19, 0xb8, 0x58, 0x52, 0x5e, 0x92, 0x36, 0x6e, 0x2c, 0x3c,
	0xb3, 0x57, 0x14, 0xeb, 0x26, 0x3b, 0x82, 0x7f, 0xb8, 0xaa, 0x50, 0x52, 0x85, 0x18, 0x2a, 0x7d,
	0x2b, 0xaa, 0x8f, 0x63, 0x51, 0xe1, 0x99, 0x41, 0x37, 0x1b, 0xfc, 0x99, 0xe3, 0x12, 0xf6, 0xba,
	0xe6, 0x3a, 0xc8, 0x31, 0x00, 0x36, 0x5d, 0xe5, 0xae, 0x86, 0x6d, 0xdb, 0x61, 0x8d, 0x7f, 0xf1,
	0xe5, 0x80, 0x77, 0x73, 0x5d, 0x35, 0xef, 0x79, 0xf1, 0x9e, 0xa9, 0xab, 0x2f, 0xc1, 0x6b, 0xad,
	0xc6, 0xf6, 0xed, 0xaf, 0xdf, 0xae, 0x13, 0xcc, 0x7a, 0xd4, 0x3a, 0x46, 0x0c, 0x93, 0x76, 0x40,
	0xd6, 0xfa, 0xf0, 0x63, 0xcb, 0xe0, 0xa0, 0x4f, 0x36, 0xc0, 0x95, 0xab, 0xef, 0x79, 0xfe, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xc1, 0x82, 0xb8, 0xfe, 0x5c, 0x02, 0x00, 0x00,
}
