FROM ubuntu:14.04
MAINTAINER me@simonrozet.com
RUN \
  apt-get -yqq --no-install-recommends install ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ADD /bin/k8s-operatord /k8s-operatord
ADD /tmp/operatord /
ENV PORT 3000
EXPOSE 3000
ENTRYPOINT ["/operatord"]
