FROM docker.dev.pardot.com/base/ubuntu:16.04
VOLUME ["/data"]
WORKDIR "/data"
RUN \
  apt-get update \
  && \
    apt-get install -y --no-install-recommends \
      devscripts \
      git \
      file \
      shellcheck
