FROM docker.dev.pardot.com/base/centos:7
ENV JFROG_CLI_VERSION=1.1.0
ENV JFROG_CLI_SHA256=e7b47d08bb1b1cc506f3334dfafeac28c4e3886412b6527d12ceed61bd28007e
ENV JFROG_CLI_URL=https://bintray.com/jfrog/jfrog-cli-go/download_file?file_path=${JFROG_CLI_VERSION}%2Fjfrog-cli-linux-amd64%2Fjfrog
ENTRYPOINT ["jfrog"]
CMD ["--help"]
RUN \
  curl -fsSL "$JFROG_CLI_URL" -o /usr/bin/jfrog \
  && \
    echo "$JFROG_CLI_SHA256  /usr/bin/jfrog" | sha256sum -c - \
  && \
    chmod +x /usr/bin/jfrog
