FROM srozet/operator/grpc
MAINTAINER Simon Rozet <me@simonrozet.com>
ENV GOROOT /usr/local/go
ENV GOBIN $GOPATH/bin
ENV OPERATOR_VERSION master
ADD . $GOPATH/src/github.com/sr/operator
RUN \
  cd $GOPATH/src/github.com/sr/operator \
  && git reset --hard $OPERATOR_VERSION \
  && git clean -fdx \
  && make ci
