FROM scratch
COPY /operatord /app/operatord
COPY /etc/ca-bundle.crt /etc/pki/tls/certs/ca-bundle.crt
EXPOSE 9000
EXPOSE 8080
CMD ["/app/operatord","-addr-grpc","0.0.0.0:9000","-addr-http","0.0.0.0:8080"]
