FROM grpc/node:0.11
MAINTAINER me@simonrozet.com
RUN \
  apt-get install -y --no-install-recommends \
    build-essential \
    libicu-dev \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/cache
ADD /src/hubot /hubot
WORKDIR /hubot
RUN npm install
ENTRYPOINT ["bin/hubot"]
