FROM scratch
MAINTAINER me@simonrozet.com
COPY /bin/k8s-operatord /k8s-operatord
COPY /tmp/operatord /operatord
COPY /etc/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENV PORT :3000
EXPOSE 3000
ENTRYPOINT ["/operatord"]
