FROM docker.dev.pardot.com/base/bread/ubuntu:wily
VOLUME ["/data"]
WORKDIR "/data"
RUN \
  apt-get update \
  && \
    apt-get install -y --no-install-recommends \
      devscripts \
      git \
      file \
      shellcheck
