// Code generated by protoc-gen-operatord.
package main

import (
	"fmt"
	"os"

	buildkite "github.com/sr/operator/src/services/buildkite"

	gcloud "github.com/sr/operator/src/services/gcloud"

	papertrail "github.com/sr/operator/src/services/papertrail"

	"github.com/sr/operator/src/operator"
	"go.pedge.io/env"
	"google.golang.org/grpc"
)

func run() error {
	config, err := operator.NewConfigFromEnv()
	if err != nil {
		return err
	}
	rpcServer := grpc.NewServer()
	logger := operator.NewLogger()
	registry := operator.NewMetricsRegistry()
	instrumentator := operator.NewInstrumentator(logger, registry)
	server := operator.NewServer(rpcServer, config, logger, instrumentator)

	buildkiteEnv := &buildkite.Env{}
	if err := env.Populate(buildkiteEnv); err != nil {
		server.LogServiceStartupError("buildkite", err)
	} else {
		if buildkiteServer, err := buildkite.NewAPIServer(buildkiteEnv); err != nil {
			server.LogServiceStartupError("buildkite", err)
		} else {
			instrumented := buildkite.NewInstrumentedAPIServer(instrumentator, buildkiteServer)
			buildkite.RegisterBuildkiteServiceServer(rpcServer, instrumented)
		}
	}

	gcloudEnv := &gcloud.Env{}
	if err := env.Populate(gcloudEnv); err != nil {
		server.LogServiceStartupError("gcloud", err)
	} else {
		if gcloudServer, err := gcloud.NewAPIServer(gcloudEnv); err != nil {
			server.LogServiceStartupError("gcloud", err)
		} else {
			instrumented := gcloud.NewInstrumentedAPIServer(instrumentator, gcloudServer)
			gcloud.RegisterGCloudServiceServer(rpcServer, instrumented)
		}
	}

	papertrailEnv := &papertrail.Env{}
	if err := env.Populate(papertrailEnv); err != nil {
		server.LogServiceStartupError("papertrail", err)
	} else {
		if papertrailServer, err := papertrail.NewAPIServer(papertrailEnv); err != nil {
			server.LogServiceStartupError("papertrail", err)
		} else {
			instrumented := papertrail.NewInstrumentedAPIServer(instrumentator, papertrailServer)
			papertrail.RegisterPapertrailServiceServer(rpcServer, instrumented)
		}
	}
	return server.Serve()
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "operatord: %s\n", err)
		os.Exit(1)
	}
}
