source "https://artifactory.dev.pardot.com/artifactory/api/gems/pd-gem/"

gem "lita", "4.7.0"
gem "lita-hipchat", "3.0.2"

gem "pagerduty", "~>2.1.0"

gem "lita-zabbix", path: "plugins/lita-zabbix"

group :test do
  gem "rack-test", "~> 0.6.3"
  gem "rspec", "~> 3.4"
  gem "webmock", "~> 1.23"
end

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
