// Code generated by protoc-gen-operatord
package main

import (
	"time"

	"github.com/sr/operator"
	"golang.org/x/net/context"

	servicepkg "chatops/ping"
)

type instrumentedpingerPinger struct {
	instrumenter operator.Instrumenter
	server       servicepkg.PingerServer
}

// Ping instruments the Pinger.Ping method.
func (a *instrumentedpingerPinger) Ping(
	ctx context.Context,
	request *servicepkg.PingRequest,
) (response *servicepkg.PingResponse, err error) {
	defer func(start time.Time) {
		a.instrumenter.Instrument(
			operator.NewRequest(
				request.Source,
				"pinger",
				"Ping",
				"PingRequest",
				"PingResponse",
				err,
				start,
			),
		)
	}(time.Now())
	return a.server.Ping(ctx, request)
}
