#!/usr/bin/env bash
set -euo pipefail
set -x
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.."; pwd)"

git subrepo push src/changeling --force -r https://git.heroku.com/pardot-changeling-production.git -b master
