#!/bin/sh
#/ Usage: . etc/shrc
#/ Setup the shell environment for working with the BREAD repo.

# Use the default (as of Go 1.8) GOPATH unless it is already set
if [ -z "${GOPATH:-""}" ]; then
    GOPATH="${HOME}/go"
    PATH="${GOPATH}/bin:${PATH}"
    export GOPATH PATH
fi

# Default to 'sfdc-aloha' Heroku organization unless it is already set
if [ -z "${HEROKU_ORGANIZATION:-""}" ]; then
    HEROKU_ORGANIZATION="sfdc-aloha"
    export HEROKU_ORGANIZATION
fi

: "${BREAD:="${GOPATH}/src/git.dev.pardot.com/Pardot/bread"}"
export BREAD

# Add utilities to the PATH
PATH="${BREAD}/bin:$PATH"
export PATH

# Quickly cd into any subtree within the BREAD repository:
#
#   $ pwd
#   /Users/srozet
#   $ cd jib
#   /Users/srozet/go/src/git.dev.pardot.com/Pardot/bread/jib
CDPATH=".:${BREAD}"
export CDPATH

test -f "$BREAD/etc/secrets" &&
. "$BREAD/etc/secrets"

true
