#!/bin/sh
#/ Usage: . etc/shrc
#/ Setup the shell environment for working with the Pardot/infrastructure repo.

# Directory where the Pardot/infrastructure is checked out.
INFRA_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Directory for BREAD-team specific projects
BREAD_DIR="${INFRA_REPO_DIR}/bread"

# Use the default (as of Go 1.8) GOPATH unless it is already set
if [ -z "${GOPATH:-""}" ]; then
    GOPATH="${HOME}/go"
    PATH="${GOPATH}/bin:${PATH}"
    export GOPATH PATH
fi

# Default to 'sfdc-aloha' Heroku organization unless it is already set
if [ -z "${HEROKU_ORGANIZATION:-""}" ]; then
    HEROKU_ORGANIZATION="sfdc-aloha"
    export HEROKU_ORGANIZATION
fi

# Add utilities to the PATH
PATH="${INFRA_REPO_DIR}/bin:${BREAD_DIR}/bin:${PATH}"
export PATH

# Quickly cd into any subtree within the infrastructure repository:
#
#   $ pwd
#   /Users/srozet
#   $ cd jib
#   /Users/srozet/go/src/git.dev.pardot.com/Pardot/infrastructure/bread/jib
CDPATH=".:${INFRA_REPO_DIR}"
export CDPATH

test -f "${BREAD_DIR}/etc/secrets" &&
. "${BREAD_DIR}/etc/secrets"

true
