// Code generated by protoc-gen-go.
// source: pb/bamboo.proto
// DO NOT EDIT!

/*
Package breadpb is a generated protocol buffer package.

It is generated from these files:
	pb/bamboo.proto
	pb/bread.proto
	pb/deploy.proto
	pb/ping.proto

It has these top-level messages:
	ListBuildsRequest
	ListBuildsResponse
	OperatorRequest
	OperatorMessage
	HTTPRequest
	ServerStartupNotice
	ServiceStartupError
	ListAppsRequest
	TriggerRequest
	TriggerResponse
	OtpRequest
	PingRequest
	WhoamiRequest
*/
package breadpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListBuildsRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Plan    string            `protobuf:"bytes,2,opt,name=plan" json:"plan,omitempty"`
}

func (m *ListBuildsRequest) Reset()                    { *m = ListBuildsRequest{} }
func (m *ListBuildsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBuildsRequest) ProtoMessage()               {}
func (*ListBuildsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListBuildsRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type ListBuildsResponse struct {
	Message string `protobuf:"bytes,1,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *ListBuildsResponse) Reset()                    { *m = ListBuildsResponse{} }
func (m *ListBuildsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBuildsResponse) ProtoMessage()               {}
func (*ListBuildsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ListBuildsRequest)(nil), "bread.ListBuildsRequest")
	proto.RegisterType((*ListBuildsResponse)(nil), "bread.ListBuildsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Bamboo service

type BambooClient interface {
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
}

type bambooClient struct {
	cc *grpc.ClientConn
}

func NewBambooClient(cc *grpc.ClientConn) BambooClient {
	return &bambooClient{cc}
}

func (c *bambooClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	out := new(ListBuildsResponse)
	err := grpc.Invoke(ctx, "/bread.Bamboo/ListBuilds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bamboo service

type BambooServer interface {
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
}

func RegisterBambooServer(s *grpc.Server, srv BambooServer) {
	s.RegisterService(&_Bamboo_serviceDesc, srv)
}

func _Bamboo_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BambooServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bread.Bamboo/ListBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BambooServer).ListBuilds(ctx, req.(*ListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bamboo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bread.Bamboo",
	HandlerType: (*BambooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBuilds",
			Handler:    _Bamboo_ListBuilds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("pb/bamboo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x4f,
	0x4a, 0xcc, 0x4d, 0xca, 0xcf, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2a, 0x4a,
	0x4d, 0x4c, 0x91, 0xe2, 0xcb, 0x2f, 0x48, 0x2d, 0x4a, 0x2c, 0xc9, 0x2f, 0x82, 0x08, 0x2b, 0x85,
	0x70, 0x09, 0xfa, 0x64, 0x16, 0x97, 0x38, 0x95, 0x66, 0xe6, 0xa4, 0x14, 0x07, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0x69, 0x73, 0xb1, 0x17, 0x41, 0x98, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0x82, 0x7a, 0x70, 0x6d, 0x50, 0x35, 0x41, 0x30, 0x15, 0x42, 0x42, 0x5c, 0x2c, 0x05, 0x39,
	0x89, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x1e, 0x97, 0x10, 0xb2,
	0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xbe, 0xa9, 0xc5, 0xc5, 0x89,
	0xe9, 0xa9, 0x60, 0x63, 0x39, 0x83, 0xd8, 0x73, 0x21, 0x5c, 0xa3, 0x60, 0x2e, 0x36, 0x27, 0xb0,
	0x63, 0x85, 0x1c, 0xb9, 0xb8, 0x10, 0x3a, 0x85, 0x24, 0xf4, 0xc0, 0xae, 0xd6, 0xc3, 0x70, 0xa2,
	0x94, 0x24, 0x16, 0x19, 0x88, 0x35, 0x52, 0x6c, 0x93, 0x9a, 0x24, 0x99, 0x92, 0x33, 0x9d, 0x38,
	0xa3, 0xd8, 0xc1, 0x6a, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x9e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0xbc, 0xad, 0x9a, 0x16, 0x01, 0x00, 0x00,
}
