// Code generated by protoc-gen-go.
// source: pb/ping.proto
// DO NOT EDIT!

package breadpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OtpRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *OtpRequest) Reset()                    { *m = OtpRequest{} }
func (m *OtpRequest) String() string            { return proto.CompactTextString(m) }
func (*OtpRequest) ProtoMessage()               {}
func (*OtpRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *OtpRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type PingRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Arg1    string            `protobuf:"bytes,2,opt,name=arg1" json:"arg1,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *PingRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type SlowLorisRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Wait    string            `protobuf:"bytes,2,opt,name=wait" json:"wait,omitempty"`
}

func (m *SlowLorisRequest) Reset()                    { *m = SlowLorisRequest{} }
func (m *SlowLorisRequest) String() string            { return proto.CompactTextString(m) }
func (*SlowLorisRequest) ProtoMessage()               {}
func (*SlowLorisRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *SlowLorisRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type WhoamiRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *WhoamiRequest) Reset()                    { *m = WhoamiRequest{} }
func (m *WhoamiRequest) String() string            { return proto.CompactTextString(m) }
func (*WhoamiRequest) ProtoMessage()               {}
func (*WhoamiRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *WhoamiRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*OtpRequest)(nil), "bread.OtpRequest")
	proto.RegisterType((*PingRequest)(nil), "bread.PingRequest")
	proto.RegisterType((*SlowLorisRequest)(nil), "bread.SlowLorisRequest")
	proto.RegisterType((*WhoamiRequest)(nil), "bread.WhoamiRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Ping service

type PingClient interface {
	Otp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*operator.Response, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*operator.Response, error)
	SlowLoris(ctx context.Context, in *SlowLorisRequest, opts ...grpc.CallOption) (*operator.Response, error)
	Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*operator.Response, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) Otp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/bread.Ping/Otp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/bread.Ping/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) SlowLoris(ctx context.Context, in *SlowLorisRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/bread.Ping/SlowLoris", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/bread.Ping/Whoami", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ping service

type PingServer interface {
	Otp(context.Context, *OtpRequest) (*operator.Response, error)
	Ping(context.Context, *PingRequest) (*operator.Response, error)
	SlowLoris(context.Context, *SlowLorisRequest) (*operator.Response, error)
	Whoami(context.Context, *WhoamiRequest) (*operator.Response, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_Otp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Otp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bread.Ping/Otp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Otp(ctx, req.(*OtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bread.Ping/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_SlowLoris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlowLorisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SlowLoris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bread.Ping/SlowLoris",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SlowLoris(ctx, req.(*SlowLorisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bread.Ping/Whoami",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Whoami(ctx, req.(*WhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bread.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Otp",
			Handler:    _Ping_Otp_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Ping_Ping_Handler,
		},
		{
			MethodName: "SlowLoris",
			Handler:    _Ping_SlowLoris_Handler,
		},
		{
			MethodName: "Whoami",
			Handler:    _Ping_Whoami_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor2,
}

func init() { proto.RegisterFile("pb/ping.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xd6, 0x96, 0x4c, 0x29, 0xd8, 0x41, 0xb0, 0xf4, 0x54, 0x02, 0x42, 0x41, 0xd9,
	0x60, 0xbc, 0x28, 0x78, 0xf2, 0x2c, 0x56, 0xd2, 0x83, 0xe0, 0x6d, 0x57, 0x97, 0x74, 0xc1, 0x66,
	0xc6, 0xdd, 0x2d, 0xfd, 0x9f, 0xfe, 0x22, 0x69, 0xb2, 0x6d, 0xa3, 0xe4, 0x94, 0xdb, 0x3b, 0x7c,
	0xdf, 0xc0, 0x7b, 0x0c, 0x8c, 0x58, 0xa5, 0x6c, 0xca, 0x42, 0xb0, 0x25, 0x4f, 0x78, 0xa6, 0xac,
	0x96, 0x9f, 0xd3, 0xab, 0xc2, 0xf8, 0xd5, 0x46, 0x89, 0x0f, 0x5a, 0xa7, 0xce, 0xa6, 0xc4, 0xda,
	0x4a, 0x4f, 0xc7, 0x50, 0xd3, 0xc9, 0x03, 0xc0, 0xc2, 0x73, 0xae, 0xbf, 0x37, 0xda, 0x79, 0xbc,
	0x86, 0x81, 0xad, 0xe3, 0x24, 0x9a, 0x45, 0xf3, 0x61, 0x36, 0x16, 0x07, 0x3e, 0x30, 0xf9, 0x9e,
	0x48, 0x5e, 0x60, 0xf8, 0x6a, 0xca, 0xa2, 0x8b, 0x8b, 0x08, 0x3d, 0x69, 0x8b, 0xdb, 0xc9, 0xc9,
	0x2c, 0x9a, 0xc7, 0x79, 0x95, 0x93, 0x25, 0x9c, 0x2f, 0xbf, 0x68, 0xfb, 0x4c, 0xd6, 0xb8, 0xae,
	0x47, 0xb7, 0xd2, 0xf8, 0xfd, 0xd1, 0x5d, 0x4e, 0x1e, 0x61, 0xf4, 0xb6, 0x22, 0xb9, 0x36, 0x5d,
	0x2e, 0x66, 0x3f, 0x11, 0xf4, 0x76, 0x1d, 0xf1, 0x06, 0x4e, 0x17, 0x9e, 0x71, 0x2c, 0xaa, 0x71,
	0xc5, 0x71, 0xb2, 0x29, 0x36, 0x75, 0xc7, 0x54, 0x3a, 0x8d, 0x22, 0x58, 0x18, 0xf0, 0xc6, 0x4c,
	0xad, 0xfc, 0x3d, 0xc4, 0x87, 0xe6, 0x78, 0x19, 0xa4, 0xff, 0x5b, 0xb4, 0x9a, 0x19, 0xf4, 0xeb,
	0x7a, 0x78, 0x11, 0xb4, 0x3f, 0x6d, 0xdb, 0x9c, 0xa7, 0xf8, 0x7d, 0x50, 0xa1, 0xac, 0x54, 0xbf,
	0x7a, 0x82, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xfd, 0x54, 0x78, 0x43, 0x02, 0x00,
	0x00,
}
