package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"bread/swagger/client/canoe"
)

// Default config canoe proto HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new config canoe proto HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ConfigCanoeProto {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new config canoe proto client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *ConfigCanoeProto {
	cli := new(ConfigCanoeProto)
	cli.Transport = transport

	cli.Canoe = canoe.New(transport, formats)

	return cli
}

// ConfigCanoeProto is a client for config canoe proto
type ConfigCanoeProto struct {
	Canoe *canoe.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ConfigCanoeProto) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Canoe.SetTransport(transport)

}
