// Code generated by protoc-gen-go.
// source: gcloud/gcloud.proto
// DO NOT EDIT!

/*
Package gcloud is a generated protocol buffer package.

It is generated from these files:
	gcloud/gcloud.proto

It has these top-level messages:
	GcloudServiceConfig
	CreateDevInstanceRequest
	CreateDevInstanceResponse
	StopRequest
	StopResponse
	Instance
	ListInstancesRequest
	ListInstancesResponse
*/
package gcloud

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type GcloudServiceConfig struct {
	ProjectId      string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DefaultZone    string `protobuf:"bytes,2,opt,name=default_zone,json=defaultZone" json:"default_zone,omitempty"`
	DefaultNetwork string `protobuf:"bytes,3,opt,name=default_network,json=defaultNetwork" json:"default_network,omitempty"`
	// TODO(sr) Allow listing all available custom images
	// TODO(sr) Use the most recent image by default
	// TODO(sr) Allow to override this per request
	DefaultImage string `protobuf:"bytes,4,opt,name=default_image,json=defaultImage" json:"default_image,omitempty"`
	// TODO(sr) Allow overriding this via request parameter
	// TODO(sr) Provider map (e.g. small = n1-standard, large = n2-standard, ...)
	DefaultMachineType  string `protobuf:"bytes,5,opt,name=default_machine_type,json=defaultMachineType" json:"default_machine_type,omitempty"`
	ServiceAccountEmail string `protobuf:"bytes,6,opt,name=service_account_email,json=serviceAccountEmail" json:"service_account_email,omitempty"`
	StartupScript       string `protobuf:"bytes,7,opt,name=startup_script,json=startupScript" json:"startup_script,omitempty"`
}

func (m *GcloudServiceConfig) Reset()                    { *m = GcloudServiceConfig{} }
func (m *GcloudServiceConfig) String() string            { return proto.CompactTextString(m) }
func (*GcloudServiceConfig) ProtoMessage()               {}
func (*GcloudServiceConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateDevInstanceRequest struct {
	Source *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
}

func (m *CreateDevInstanceRequest) Reset()                    { *m = CreateDevInstanceRequest{} }
func (m *CreateDevInstanceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDevInstanceRequest) ProtoMessage()               {}
func (*CreateDevInstanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateDevInstanceRequest) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type CreateDevInstanceResponse struct {
	Output *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *CreateDevInstanceResponse) Reset()                    { *m = CreateDevInstanceResponse{} }
func (m *CreateDevInstanceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDevInstanceResponse) ProtoMessage()               {}
func (*CreateDevInstanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateDevInstanceResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type StopRequest struct {
	Source   *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Instance string           `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`
	Zone     string           `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StopRequest) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type StopResponse struct {
	Output *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StopResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type Instance struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Zone   string `protobuf:"bytes,4,opt,name=zone" json:"zone,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ListInstancesRequest struct {
	Source    *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	ProjectId string           `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *ListInstancesRequest) Reset()                    { *m = ListInstancesRequest{} }
func (m *ListInstancesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListInstancesRequest) ProtoMessage()               {}
func (*ListInstancesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListInstancesRequest) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type ListInstancesResponse struct {
	Output  *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
	Source  *operator.Source `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Objects []*Instance      `protobuf:"bytes,3,rep,name=objects" json:"objects,omitempty"`
}

func (m *ListInstancesResponse) Reset()                    { *m = ListInstancesResponse{} }
func (m *ListInstancesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListInstancesResponse) ProtoMessage()               {}
func (*ListInstancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListInstancesResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ListInstancesResponse) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ListInstancesResponse) GetObjects() []*Instance {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*GcloudServiceConfig)(nil), "gcloud.GcloudServiceConfig")
	proto.RegisterType((*CreateDevInstanceRequest)(nil), "gcloud.CreateDevInstanceRequest")
	proto.RegisterType((*CreateDevInstanceResponse)(nil), "gcloud.CreateDevInstanceResponse")
	proto.RegisterType((*StopRequest)(nil), "gcloud.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "gcloud.StopResponse")
	proto.RegisterType((*Instance)(nil), "gcloud.Instance")
	proto.RegisterType((*ListInstancesRequest)(nil), "gcloud.ListInstancesRequest")
	proto.RegisterType((*ListInstancesResponse)(nil), "gcloud.ListInstancesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for GcloudService service

type GcloudServiceClient interface {
	// Provision a development instance using the configured image.
	CreateDevInstance(ctx context.Context, in *CreateDevInstanceRequest, opts ...grpc.CallOption) (*CreateDevInstanceResponse, error)
	// List all instances under the configured project.
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// Stop a running instance.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type gcloudServiceClient struct {
	cc *grpc.ClientConn
}

func NewGcloudServiceClient(cc *grpc.ClientConn) GcloudServiceClient {
	return &gcloudServiceClient{cc}
}

func (c *gcloudServiceClient) CreateDevInstance(ctx context.Context, in *CreateDevInstanceRequest, opts ...grpc.CallOption) (*CreateDevInstanceResponse, error) {
	out := new(CreateDevInstanceResponse)
	err := grpc.Invoke(ctx, "/gcloud.GcloudService/CreateDevInstance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcloudServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	out := new(ListInstancesResponse)
	err := grpc.Invoke(ctx, "/gcloud.GcloudService/ListInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcloudServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := grpc.Invoke(ctx, "/gcloud.GcloudService/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GcloudService service

type GcloudServiceServer interface {
	// Provision a development instance using the configured image.
	CreateDevInstance(context.Context, *CreateDevInstanceRequest) (*CreateDevInstanceResponse, error)
	// List all instances under the configured project.
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// Stop a running instance.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
}

func RegisterGcloudServiceServer(s *grpc.Server, srv GcloudServiceServer) {
	s.RegisterService(&_GcloudService_serviceDesc, srv)
}

func _GcloudService_CreateDevInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDevInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcloudServiceServer).CreateDevInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gcloud.GcloudService/CreateDevInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcloudServiceServer).CreateDevInstance(ctx, req.(*CreateDevInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GcloudService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcloudServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gcloud.GcloudService/ListInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcloudServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GcloudService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcloudServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gcloud.GcloudService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcloudServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GcloudService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcloud.GcloudService",
	HandlerType: (*GcloudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDevInstance",
			Handler:    _GcloudService_CreateDevInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _GcloudService_ListInstances_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GcloudService_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x55, 0xdc, 0x7c, 0x69, 0x7b, 0xd3, 0xe4, 0x83, 0x9b, 0x14, 0xb9, 0x16, 0x95, 0x5a, 0x23,
	0x44, 0xc5, 0xa2, 0x40, 0xd8, 0xb0, 0x45, 0x6d, 0x85, 0x22, 0x15, 0x90, 0x12, 0x16, 0xa8, 0x1b,
	0x6b, 0xea, 0xdc, 0x06, 0x43, 0xe2, 0x31, 0x9e, 0xeb, 0x22, 0x58, 0xf2, 0x08, 0x6c, 0x78, 0x0f,
	0x1e, 0x8e, 0x35, 0xf6, 0xfc, 0x58, 0x49, 0x7f, 0x40, 0x59, 0x79, 0xe6, 0x9c, 0x33, 0xf7, 0x6f,
	0x8e, 0x07, 0x7a, 0xd3, 0x78, 0x26, 0x8b, 0xc9, 0x13, 0xf3, 0x39, 0xcc, 0x72, 0xc9, 0x12, 0x5b,
	0x66, 0x17, 0x74, 0x65, 0x46, 0xb9, 0x60, 0x99, 0x1b, 0x3c, 0xfc, 0xe5, 0x41, 0xef, 0x95, 0xa6,
	0xc6, 0x94, 0x5f, 0x26, 0x31, 0x1d, 0xc9, 0xf4, 0x22, 0x99, 0xe2, 0x2e, 0x40, 0x29, 0xf8, 0x48,
	0x31, 0x47, 0xc9, 0xc4, 0x6f, 0xec, 0x35, 0x0e, 0x36, 0x47, 0x9b, 0x16, 0x19, 0x4e, 0x70, 0x1f,
	0xb6, 0x26, 0x74, 0x21, 0x8a, 0x19, 0x47, 0xdf, 0x64, 0x4a, 0xbe, 0xa7, 0x05, 0x6d, 0x8b, 0x9d,
	0x95, 0x10, 0x3e, 0x82, 0xff, 0x9d, 0x24, 0x25, 0xfe, 0x22, 0xf3, 0x4f, 0xfe, 0x9a, 0x56, 0x75,
	0x2d, 0xfc, 0xc6, 0xa0, 0xf8, 0x00, 0x3a, 0x4e, 0x98, 0xcc, 0xc5, 0x94, 0xfc, 0xa6, 0x96, 0xb9,
	0x04, 0xc3, 0x0a, 0xc3, 0xa7, 0xd0, 0x77, 0xa2, 0xb9, 0x88, 0x3f, 0x24, 0x29, 0x45, 0xfc, 0x35,
	0x23, 0xff, 0x3f, 0xad, 0x45, 0xcb, 0xbd, 0x36, 0xd4, 0xbb, 0x92, 0xc1, 0x01, 0x6c, 0x2b, 0xd3,
	0x52, 0x24, 0xe2, 0x58, 0x16, 0x29, 0x47, 0x34, 0x17, 0xc9, 0xcc, 0x6f, 0xe9, 0x23, 0x3d, 0x4b,
	0xbe, 0x34, 0xdc, 0x49, 0x45, 0xe1, 0x43, 0xe8, 0x2a, 0x16, 0x39, 0x17, 0x59, 0xa4, 0xe2, 0x3c,
	0xc9, 0xd8, 0x5f, 0xd7, 0xe2, 0x8e, 0x45, 0xc7, 0x1a, 0x0c, 0x8f, 0xc1, 0x3f, 0xca, 0x49, 0x30,
	0x1d, 0xd3, 0xe5, 0x30, 0x2d, 0xb9, 0x34, 0xa6, 0x11, 0x7d, 0x2e, 0x48, 0x31, 0x1e, 0x40, 0x4b,
	0xc9, 0x22, 0x8f, 0x49, 0x0f, 0xad, 0x3d, 0xb8, 0x73, 0x58, 0x4f, 0x7c, 0xac, 0xf1, 0x91, 0xe5,
	0xc3, 0x13, 0xd8, 0xb9, 0x21, 0x8a, 0xca, 0x64, 0xaa, 0xa8, 0x0a, 0x23, 0x0b, 0xce, 0x0a, 0xbe,
	0x1e, 0xe6, 0xad, 0xc6, 0x47, 0x96, 0x0f, 0xa7, 0xd0, 0x1e, 0xb3, 0xcc, 0x56, 0xce, 0x8f, 0x01,
	0x6c, 0x24, 0x36, 0xad, 0xbd, 0xbf, 0x7a, 0x8f, 0x08, 0x4d, 0x7d, 0xaf, 0xe6, 0xc6, 0xf4, 0x3a,
	0x7c, 0x01, 0x5b, 0x26, 0xd1, 0xca, 0x25, 0x9e, 0xc1, 0x86, 0x6b, 0x10, 0xbb, 0xe0, 0xd5, 0x86,
	0x2a, 0x57, 0x55, 0xa6, 0x54, 0xcc, 0x5d, 0x05, 0x7a, 0x8d, 0xf7, 0xca, 0x1e, 0x58, 0x70, 0xa1,
	0x6c, 0x7e, 0xbb, 0xab, 0xab, 0x6a, 0x2e, 0x54, 0x15, 0x41, 0xff, 0x34, 0x51, 0xec, 0xe2, 0xab,
	0xd5, 0xe7, 0xb0, 0x6c, 0x75, 0xef, 0x8a, 0xd5, 0xc3, 0x9f, 0x0d, 0xd8, 0xbe, 0x92, 0x61, 0xd5,
	0x01, 0x2c, 0x14, 0xe3, 0xfd, 0xa3, 0x98, 0xc7, 0xb0, 0x2e, 0xcf, 0xab, 0xcc, 0x55, 0xef, 0x6b,
	0x5a, 0x6a, 0xff, 0xe3, 0xda, 0x22, 0x4e, 0x30, 0xf8, 0xdd, 0x80, 0xce, 0xd2, 0xbf, 0x8b, 0xef,
	0xe1, 0xee, 0x35, 0x4b, 0xe1, 0x9e, 0x8b, 0x70, 0x9b, 0x67, 0x83, 0xfd, 0xbf, 0x28, 0x6c, 0xaf,
	0xa7, 0xd0, 0x59, 0x1a, 0x02, 0xde, 0x77, 0x67, 0x6e, 0x9a, 0x7e, 0xb0, 0x7b, 0x0b, 0x6b, 0xa3,
	0x3d, 0x83, 0x66, 0x65, 0x25, 0xec, 0x39, 0xd9, 0x82, 0x83, 0x83, 0xfe, 0x32, 0x68, 0x8e, 0x04,
	0xf0, 0xe3, 0xfb, 0x8e, 0x7d, 0xc4, 0xce, 0x5b, 0xfa, 0xed, 0x7a, 0xfe, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x60, 0x5a, 0x4d, 0xdd, 0xea, 0x04, 0x00, 0x00,
}
