#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "===> Setting up DB..."
# reset database to a fresh state.
bin/rake db:create db:migrate

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  # Only run in development environments
  echo "===> Adding projects"
  bin/rake canoe:create_projects
  echo "===> Adding development targets"
  bin/rake canoe:create_targets
fi

echo "==> App is now ready to go!"
