// Code generated by protoc-gen-go.
// source: services/gcloud/gcloud.proto
// DO NOT EDIT!

/*
Package gcloud is a generated protocol buffer package.

It is generated from these files:
	services/gcloud/gcloud.proto

It has these top-level messages:
	CreateContainerClusterRequest
	CreateContainerClusterResponse
	Instance
	ListInstancesRequest
	ListInstancesResponse
*/
package gcloud

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreateContainerClusterRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id" json:"project_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NodeCount string `protobuf:"bytes,3,opt,name=node_count" json:"node_count,omitempty"`
	Zone      string `protobuf:"bytes,4,opt,name=zone" json:"zone,omitempty"`
}

func (m *CreateContainerClusterRequest) Reset()                    { *m = CreateContainerClusterRequest{} }
func (m *CreateContainerClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerClusterRequest) ProtoMessage()               {}
func (*CreateContainerClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateContainerClusterResponse struct {
	Output *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *CreateContainerClusterResponse) Reset()                    { *m = CreateContainerClusterResponse{} }
func (m *CreateContainerClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerClusterResponse) ProtoMessage()               {}
func (*CreateContainerClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateContainerClusterResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type Instance struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Zone   string `protobuf:"bytes,4,opt,name=zone" json:"zone,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListInstancesRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id" json:"project_id,omitempty"`
}

func (m *ListInstancesRequest) Reset()                    { *m = ListInstancesRequest{} }
func (m *ListInstancesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListInstancesRequest) ProtoMessage()               {}
func (*ListInstancesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListInstancesResponse struct {
	Output  *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
	Objects []*Instance      `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
}

func (m *ListInstancesResponse) Reset()                    { *m = ListInstancesResponse{} }
func (m *ListInstancesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListInstancesResponse) ProtoMessage()               {}
func (*ListInstancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListInstancesResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ListInstancesResponse) GetObjects() []*Instance {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateContainerClusterRequest)(nil), "gcloud.CreateContainerClusterRequest")
	proto.RegisterType((*CreateContainerClusterResponse)(nil), "gcloud.CreateContainerClusterResponse")
	proto.RegisterType((*Instance)(nil), "gcloud.Instance")
	proto.RegisterType((*ListInstancesRequest)(nil), "gcloud.ListInstancesRequest")
	proto.RegisterType((*ListInstancesResponse)(nil), "gcloud.ListInstancesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for GcloudService service

type GcloudServiceClient interface {
	CreateContainerCluster(ctx context.Context, in *CreateContainerClusterRequest, opts ...grpc.CallOption) (*CreateContainerClusterResponse, error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
}

type gcloudServiceClient struct {
	cc *grpc.ClientConn
}

func NewGcloudServiceClient(cc *grpc.ClientConn) GcloudServiceClient {
	return &gcloudServiceClient{cc}
}

func (c *gcloudServiceClient) CreateContainerCluster(ctx context.Context, in *CreateContainerClusterRequest, opts ...grpc.CallOption) (*CreateContainerClusterResponse, error) {
	out := new(CreateContainerClusterResponse)
	err := grpc.Invoke(ctx, "/gcloud.GcloudService/CreateContainerCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcloudServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	out := new(ListInstancesResponse)
	err := grpc.Invoke(ctx, "/gcloud.GcloudService/ListInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GcloudService service

type GcloudServiceServer interface {
	CreateContainerCluster(context.Context, *CreateContainerClusterRequest) (*CreateContainerClusterResponse, error)
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
}

func RegisterGcloudServiceServer(s *grpc.Server, srv GcloudServiceServer) {
	s.RegisterService(&_GcloudService_serviceDesc, srv)
}

func _GcloudService_CreateContainerCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateContainerClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GcloudServiceServer).CreateContainerCluster(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GcloudService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GcloudServiceServer).ListInstances(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _GcloudService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcloud.GcloudService",
	HandlerType: (*GcloudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainerCluster",
			Handler:    _GcloudService_CreateContainerCluster_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _GcloudService_ListInstances_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xe9, 0x07, 0xab, 0x8e, 0x56, 0x24, 0xf8, 0xb1, 0x2e, 0xad, 0xd4, 0x82, 0x22, 0x1e,
	0x5a, 0xa8, 0x6f, 0x60, 0x0f, 0x22, 0x14, 0x04, 0xbd, 0x0a, 0x65, 0x9b, 0x0e, 0x65, 0xa5, 0x66,
	0xd6, 0x64, 0xe2, 0xc1, 0xa3, 0x8f, 0xe0, 0xa3, 0xf9, 0x44, 0xa6, 0xd9, 0x8d, 0xa0, 0x74, 0xab,
	0xa7, 0xdd, 0x49, 0x7e, 0xf9, 0xcf, 0x7f, 0x3e, 0xa0, 0x6d, 0x50, 0xbf, 0x66, 0x12, 0xcd, 0x60,
	0x2e, 0x17, 0x64, 0x67, 0xe5, 0xa7, 0x9f, 0x6b, 0x62, 0x12, 0x51, 0x11, 0x25, 0x47, 0x94, 0xa3,
	0x4e, 0x99, 0xf4, 0x20, 0xfc, 0x14, 0x40, 0x4f, 0x42, 0x67, 0xa4, 0x31, 0x65, 0x1c, 0x91, 0xe2,
	0x34, 0x53, 0xa8, 0x47, 0x0b, 0x6b, 0x18, 0xf5, 0x3d, 0xbe, 0x58, 0x34, 0x2c, 0x04, 0x80, 0x23,
	0x9f, 0x50, 0xf2, 0x24, 0x9b, 0xc5, 0xb5, 0x6e, 0xed, 0x62, 0x4b, 0xec, 0x40, 0x53, 0xa5, 0xcf,
	0x18, 0xd7, 0x7d, 0xe4, 0x08, 0x45, 0x33, 0x9c, 0x48, 0xb2, 0x8a, 0xe3, 0x46, 0x20, 0xde, 0x48,
	0x61, 0xdc, 0x5c, 0x46, 0xbd, 0x6b, 0x38, 0xa9, 0x4a, 0x62, 0x72, 0x52, 0x06, 0x45, 0x17, 0x22,
	0xb2, 0x9c, 0x5b, 0xf6, 0x19, 0xb6, 0x87, 0x7b, 0xfd, 0x6f, 0x9f, 0x77, 0xfe, 0xdc, 0x69, 0x6c,
	0xde, 0x2a, 0xc3, 0xa9, 0x92, 0xe8, 0x12, 0xd6, 0x2b, 0xbc, 0xec, 0x42, 0xe4, 0x18, 0xb6, 0x66,
	0xa5, 0x8f, 0x4b, 0xd8, 0x1f, 0x67, 0x86, 0x83, 0x8e, 0x59, 0x53, 0x63, 0xef, 0x11, 0x0e, 0x7e,
	0xb1, 0xff, 0xb5, 0x2a, 0x4e, 0x61, 0x83, 0xa6, 0x4b, 0x35, 0xe3, 0x5c, 0x35, 0x3c, 0x52, 0x0e,
	0x25, 0xa8, 0x0d, 0x3f, 0x6b, 0xd0, 0xba, 0xf1, 0x67, 0x0f, 0xc5, 0xf8, 0xc4, 0x1c, 0x0e, 0x57,
	0xf7, 0x48, 0x9c, 0x85, 0xd7, 0x6b, 0x07, 0x95, 0x9c, 0xff, 0x85, 0x95, 0xfe, 0xc7, 0xd0, 0xfa,
	0x51, 0x98, 0x68, 0x87, 0x87, 0xab, 0x7a, 0x93, 0x74, 0x2a, 0x6e, 0x0b, 0xb5, 0x04, 0x3e, 0xde,
	0x8f, 0xcb, 0x25, 0x9b, 0x46, 0x7e, 0xa5, 0xae, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x5d,
	0x64, 0x30, 0x93, 0x02, 0x00, 0x00,
}
