IMPORTPATH ?= chatops/services
OPERATORD ?= $(GOPATH)/bin/operatord
OPERATORCTL ?= $(GOPATH)/bin/operatorctl
OPERATORCTL_GEN_SRC ?= $(GOPATH)/src/bread/cmd/operatorctl/main-gen.go
OPERATORD_GEN_SRC ?= $(GOPATH)/src/bread/cmd/operatord/builder-gen.go

include $(GOPATH)/src/github.com/sr/operator/operator.mk
