package canoe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"bread/swagger/models"
)

// NewCreateDeployParams creates a new CreateDeployParams object
// with the default values initialized.
func NewCreateDeployParams() *CreateDeployParams {
	var ()
	return &CreateDeployParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDeployParamsWithTimeout creates a new CreateDeployParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDeployParamsWithTimeout(timeout time.Duration) *CreateDeployParams {
	var ()
	return &CreateDeployParams{

		timeout: timeout,
	}
}

// NewCreateDeployParamsWithContext creates a new CreateDeployParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDeployParamsWithContext(ctx context.Context) *CreateDeployParams {
	var ()
	return &CreateDeployParams{

		Context: ctx,
	}
}

/*CreateDeployParams contains all the parameters to send to the API endpoint
for the create deploy operation typically these are written to a http.Request
*/
type CreateDeployParams struct {

	/*Body*/
	Body *models.CanoeCreateDeployRequest

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the create deploy params
func (o *CreateDeployParams) WithTimeout(timeout time.Duration) *CreateDeployParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create deploy params
func (o *CreateDeployParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create deploy params
func (o *CreateDeployParams) WithContext(ctx context.Context) *CreateDeployParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create deploy params
func (o *CreateDeployParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the create deploy params
func (o *CreateDeployParams) WithBody(body *models.CanoeCreateDeployRequest) *CreateDeployParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create deploy params
func (o *CreateDeployParams) SetBody(body *models.CanoeCreateDeployRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDeployParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.CanoeCreateDeployRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
