#!/usr/bin/env bash
set -euxo pipefail

currentmanifest="$(mktemp)"
git ls-files origin/master > "$currentmanifest"

ORIG_GOPATH="${GOPATH}"

git clone -b infra-repo-prep https://git.dev.pardot.com/Pardot/bread \
  "${GOPATH}/src/git.dev.pardot.com/Pardot/infrastructure"

cd "${GOPATH}/src/git.dev.pardot.com/Pardot/infrastructure"
mkdir bread
git mv -k ./* ./bread
git mv bread/bin bin

packages='
bread
bread/devenv
bread/heroku
bread/hipchat
bread/jib
bread/jib/github
bread/jira
bread/pb
bread/pb/hal9000
bread/privet
bread/generated/swagger/client
bread/generated/swagger/client/canoe
bread/generated/swagger/models
'
for pkg in $packages; do
    find . -type f -name "*.go" -a -not -path "./bread/vendor/*" -a -not -path "./bread/terraform/*" -exec \
        gofmt -w -r "\"git.dev.pardot.com/Pardot/${pkg}\" -> \"git.dev.pardot.com/Pardot/infrastructure/${pkg}\"" {} +
done

go install -v ./...

git add bread
git commit -m "Rename to git.dev.pardot.com/Pardot/infrastructure"

newmanifest="$(mktemp)"
git ls-files HEAD | sed 's/^bread\///' > "$newmanifest"
git diff --exit-code "$currentmanifest" "$newmanifest"

echo "${GOPATH}/src/git.dev.pardot.com/Pardot/infrastructure"
