// Code generated by protoc-gen-go.
// source: buildkite/buildkite.proto
// DO NOT EDIT!

/*
Package buildkite is a generated protocol buffer package.

It is generated from these files:
	buildkite/buildkite.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
	ListBuildsRequest
	ListBuildsResponse
*/
package buildkite

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type StatusRequest struct {
	Source *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	// Optional project slug.
	Slug string `protobuf:"bytes,2,opt,name=slug" json:"slug,omitempty"`
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatusRequest) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type StatusResponse struct {
	Output *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type ListBuildsRequest struct {
	Source      *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	ProjectSlug string           `protobuf:"bytes,2,opt,name=project_slug,json=projectSlug" json:"project_slug,omitempty"`
}

func (m *ListBuildsRequest) Reset()                    { *m = ListBuildsRequest{} }
func (m *ListBuildsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBuildsRequest) ProtoMessage()               {}
func (*ListBuildsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListBuildsRequest) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type ListBuildsResponse struct {
	Output *operator.Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *ListBuildsResponse) Reset()                    { *m = ListBuildsResponse{} }
func (m *ListBuildsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBuildsResponse) ProtoMessage()               {}
func (*ListBuildsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListBuildsResponse) GetOutput() *operator.Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "buildkite.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "buildkite.StatusResponse")
	proto.RegisterType((*ListBuildsRequest)(nil), "buildkite.ListBuildsRequest")
	proto.RegisterType((*ListBuildsResponse)(nil), "buildkite.ListBuildsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for BuildkiteService service

type BuildkiteServiceClient interface {
	// List the status of all (i.e. the status of the last build) of one or
	// all projects.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// List the last builds of one or all projects, optionally limited to a
	// project.
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
}

type buildkiteServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildkiteServiceClient(cc *grpc.ClientConn) BuildkiteServiceClient {
	return &buildkiteServiceClient{cc}
}

func (c *buildkiteServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/buildkite.BuildkiteService/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildkiteServiceClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	out := new(ListBuildsResponse)
	err := grpc.Invoke(ctx, "/buildkite.BuildkiteService/ListBuilds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BuildkiteService service

type BuildkiteServiceServer interface {
	// List the status of all (i.e. the status of the last build) of one or
	// all projects.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// List the last builds of one or all projects, optionally limited to a
	// project.
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
}

func RegisterBuildkiteServiceServer(s *grpc.Server, srv BuildkiteServiceServer) {
	s.RegisterService(&_BuildkiteService_serviceDesc, srv)
}

func _BuildkiteService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BuildkiteServiceServer).Status(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BuildkiteService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BuildkiteServiceServer).ListBuilds(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BuildkiteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "buildkite.BuildkiteService",
	HandlerType: (*BuildkiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _BuildkiteService_Status_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _BuildkiteService_ListBuilds_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x2a, 0xcd, 0xcc,
	0x49, 0xc9, 0xce, 0x2c, 0x49, 0xd5, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x52, 0x7c, 0xf9, 0x05, 0xa9, 0x45, 0x89, 0x25, 0xf9, 0x45, 0x10, 0x29, 0x25, 0x5f,
	0x2e, 0xde, 0xe0, 0x92, 0xc4, 0x92, 0xd2, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x0d, 0x2e, 0xb6, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23,
	0x01, 0x3d, 0xb8, 0x8e, 0x60, 0xb0, 0x78, 0x10, 0x54, 0x5e, 0x48, 0x88, 0x8b, 0xa5, 0x38, 0xa7,
	0x34, 0x5d, 0x82, 0x09, 0xa8, 0x8e, 0x33, 0x08, 0xcc, 0x56, 0xb2, 0xe2, 0xe2, 0x83, 0x19, 0x57,
	0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x0a, 0x32, 0x2f, 0xbf, 0xb4, 0xa4, 0xa0, 0xb4, 0x04, 0xd3, 0x3c,
	0x7f, 0xb0, 0x78, 0x10, 0x54, 0x5e, 0x29, 0x81, 0x4b, 0xd0, 0x27, 0xb3, 0xb8, 0xc4, 0x09, 0xe4,
	0x56, 0x32, 0x9c, 0xa3, 0xc8, 0xc5, 0x03, 0xf4, 0x52, 0x56, 0x6a, 0x72, 0x49, 0x3c, 0x92, 0xb3,
	0xb8, 0xa1, 0x62, 0xc1, 0x20, 0xd7, 0xd9, 0x71, 0x09, 0x21, 0xdb, 0x40, 0xaa, 0x0b, 0x8d, 0x56,
	0x33, 0x72, 0x09, 0x38, 0xc1, 0x82, 0x32, 0x38, 0xb5, 0xa8, 0x2c, 0x13, 0x68, 0xaf, 0x2d, 0x17,
	0x1b, 0xc4, 0xcb, 0x42, 0x12, 0x7a, 0x88, 0x80, 0x47, 0x09, 0x54, 0x29, 0x49, 0x2c, 0x32, 0x50,
	0xdb, 0x3d, 0xb9, 0xb8, 0x10, 0x6e, 0x12, 0x92, 0x41, 0x52, 0x88, 0x11, 0x18, 0x52, 0xb2, 0x38,
	0x64, 0x21, 0x46, 0x49, 0xf1, 0x4e, 0x6a, 0x92, 0x44, 0x44, 0x75, 0x12, 0x1b, 0x38, 0x86, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0x9d, 0xc7, 0xbe, 0x19, 0x02, 0x00, 0x00,
}
