#!/usr/bin/env bash
set -euo pipefail

# For testing -env-vars
PRIVET_EXAMPLE_VAR="${PRIVET_EXAMPLE_VAR-}"

printf "run-units: "
printf "PRIVET_EXAMPLE_VAR=%s " "${PRIVET_EXAMPLE_VAR}"
printf "Arguments: "
printf "'%s' " "$@"
printf "\n"
