#!/usr/bin/env ruby

require "yaml"
require "optparse"

all = false
artifactory_host = "artifactory.dev.pardot.com"
parser = OptionParser.new { |opts|
  opts.banner = "Usage: build [--all] image [image...]"

  opts.on("-a", "--all", "Build all images") do
    all = true
  end

  opts.on("--artifactory-host=HOST", "Sets the artifactory_host build argument (default: artifactory.dev.pardot.com)") do |arg|
    artifactory_host = arg
  end
}
parser.parse!

if !all && ARGV.length == 0
  puts parser.help
  abort
end

all_images = YAML.load_file(File.join(File.dirname(__FILE__), "..", "images.yml")).fetch("images")
images = all ? all_images.keys : ARGV

images.each do |image|
  unless all_images.key?(image)
    puts "error: #{image} not defined in images.yml"
    abort
  end
end

images.each do |image|
  build = all_images[image].fetch("build")

  docker_cmd = [
    File.join(File.dirname(__FILE__), "docker"),
    "build",
    "--build-arg", "artifactory_host=#{artifactory_host}",
    "-f", all_images[image].fetch("file") { File.join(build, "Dockerfile") },
    "-t", image,
    all_images[image].fetch("pull", false) ? "--pull" : nil,
    build
  ].compact

  puts "+ #{docker_cmd.inspect}"
  system(*docker_cmd)

  exit $?.exitstatus unless $?.success?
end
