#!/usr/bin/env bash
set -eo pipefail

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)

"$dir/build" --all --artifactory-host="artifactory-internal.dev.pardot.com"

head="$(git rev-parse HEAD)"
master="$(git rev-parse master)"

if [ "$head" = "$master" ]; then
  "$dir/push" --all
else
  echo "HEAD is ${head}, but master is ${master}. Skipping push."
fi
