#!/usr/bin/env ruby

require "yaml"
require "optparse"

all = false
parser = OptionParser.new { |opts|
  opts.banner = "Usage: pull [--all] image [image...]"

  opts.on("-a", "--all", "Pull all images") do
    all = true
  end
}
parser.parse!

if !all && ARGV.length == 0
  puts parser.help
  abort
end

all_images = YAML.load_file(File.join(File.dirname(__FILE__), "..", "images.yml")).fetch("images")
images = all ? all_images.keys : ARGV

images.each do |image|
  unless all_images.key?(image)
    puts "error: #{image} not defined in images.yml"
    abort
  end
end

images.each do |image|
  Process.spawn(
    File.join(File.dirname(__FILE__), "docker"),
    "pull",
    image
  )
end

statuses = Process.waitall.map(&:last)
error = statuses.detect { |s| !s.success? }
exit error.exitstatus if error