#!/usr/bin/env ruby

require "yaml"
require "optparse"

all = false
parser = OptionParser.new { |opts|
  opts.banner = "Usage: build [--all] image [image...]"

  opts.on("-a", "--all", "Build all images") do
    all = true
  end
}
parser.parse!

if !all && ARGV.length == 0
  puts parser.help
  abort
end

all_images = YAML.load_file(File.join(File.dirname(__FILE__), "..", "images.yml")).fetch("images")
images = all ? all_images.keys : ARGV

images.each do |image|
  unless all_images.key?(image)
    puts "error: #{image} not defined in images.yml"
    abort
  end
end

images.each do |image|
  system(
    File.join(File.dirname(__FILE__), "docker"),
    "push",
    image
  )

  exit $?.exitstatus unless $?.success?
end
