# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "rpms-el6" do |el6|
    el6.vm.box = "bento/centos-6.7"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.synced_folder ".", "/root/rpmbuild"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y rpmdevtools rpmlint yum-utils epel-release
    sudo yum groupinstall -y "Development Tools"
  SHELL
end
