package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CanoeCompleteTerraformDeployRequest canoe complete terraform deploy request
// swagger:model canoeCompleteTerraformDeployRequest
type CanoeCompleteTerraformDeployRequest struct {

	// deploy id
	DeployID int64 `json:"deploy_id,omitempty"`

	// request id
	RequestID string `json:"request_id,omitempty"`

	// successful
	Successful bool `json:"successful,omitempty"`

	// user email
	UserEmail string `json:"user_email,omitempty"`
}

// Validate validates this canoe complete terraform deploy request
func (m *CanoeCompleteTerraformDeployRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
