package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CanoeCreateTerraformDeployRequest canoe create terraform deploy request
// swagger:model canoeCreateTerraformDeployRequest
type CanoeCreateTerraformDeployRequest struct {

	// branch
	Branch string `json:"branch,omitempty"`

	// commit
	Commit string `json:"commit,omitempty"`

	// estate
	Estate string `json:"estate,omitempty"`

	// terraform version
	TerraformVersion string `json:"terraform_version,omitempty"`

	// user email
	UserEmail string `json:"user_email,omitempty"`
}

// Validate validates this canoe create terraform deploy request
func (m *CanoeCreateTerraformDeployRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
