// Code generated by protoc-gen-go.
// source: operator.proto
// DO NOT EDIT!

/*
Package operatorproto is a generated protocol buffer package.

It is generated from these files:
	operator.proto

It has these top-level messages:
	Source
	Room
	User
	Output
	ServerStartupNotice
	ServerStartupError
	ServiceRegistered
	ServiceStartupError
	Service
*/
package operatorproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SourceType int32

const (
	SourceType_HUBOT_SLACK SourceType = 0
	SourceType_COMMAND     SourceType = 1
)

var SourceType_name = map[int32]string{
	0: "HUBOT_SLACK",
	1: "COMMAND",
}
var SourceType_value = map[string]int32{
	"HUBOT_SLACK": 0,
	"COMMAND":     1,
}

func (x SourceType) String() string {
	return proto.EnumName(SourceType_name, int32(x))
}
func (SourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Source struct {
	Type SourceType `protobuf:"varint,1,opt,name=type,enum=operator.SourceType" json:"type,omitempty"`
	User *User      `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Room *Room      `protobuf:"bytes,3,opt,name=room" json:"room,omitempty"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Source) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Source) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type Room struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login" json:"login,omitempty"`
	RealName string `protobuf:"bytes,3,opt,name=real_name" json:"real_name,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Output struct {
	PlainText string `protobuf:"bytes,1,opt,name=PlainText" json:"PlainText,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ServerStartupNotice struct {
	Address  string     `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	Protocol string     `protobuf:"bytes,2,opt,name=Protocol" json:"Protocol,omitempty"`
	Services []*Service `protobuf:"bytes,3,rep,name=services" json:"services,omitempty"`
}

func (m *ServerStartupNotice) Reset()                    { *m = ServerStartupNotice{} }
func (m *ServerStartupNotice) String() string            { return proto.CompactTextString(m) }
func (*ServerStartupNotice) ProtoMessage()               {}
func (*ServerStartupNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServerStartupNotice) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServerStartupError struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ServerStartupError) Reset()                    { *m = ServerStartupError{} }
func (m *ServerStartupError) String() string            { return proto.CompactTextString(m) }
func (*ServerStartupError) ProtoMessage()               {}
func (*ServerStartupError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ServiceRegistered struct {
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *ServiceRegistered) Reset()                    { *m = ServiceRegistered{} }
func (m *ServiceRegistered) String() string            { return proto.CompactTextString(m) }
func (*ServiceRegistered) ProtoMessage()               {}
func (*ServiceRegistered) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceRegistered) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ServiceStartupError struct {
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ServiceStartupError) Reset()                    { *m = ServiceStartupError{} }
func (m *ServiceStartupError) String() string            { return proto.CompactTextString(m) }
func (*ServiceStartupError) ProtoMessage()               {}
func (*ServiceStartupError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServiceStartupError) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type Service struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

var E_Name = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51234,
	Name:          "operator.name",
	Tag:           "bytes,51234,opt,name=name",
}

func init() {
	proto.RegisterType((*Source)(nil), "operator.Source")
	proto.RegisterType((*Room)(nil), "operator.Room")
	proto.RegisterType((*User)(nil), "operator.User")
	proto.RegisterType((*Output)(nil), "operator.Output")
	proto.RegisterType((*ServerStartupNotice)(nil), "operator.ServerStartupNotice")
	proto.RegisterType((*ServerStartupError)(nil), "operator.ServerStartupError")
	proto.RegisterType((*ServiceRegistered)(nil), "operator.ServiceRegistered")
	proto.RegisterType((*ServiceStartupError)(nil), "operator.ServiceStartupError")
	proto.RegisterType((*Service)(nil), "operator.Service")
	proto.RegisterEnum("operator.SourceType", SourceType_name, SourceType_value)
	proto.RegisterExtension(E_Name)
}

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0xaf, 0xd2, 0x40,
	0x10, 0x17, 0xa8, 0x14, 0x06, 0xf9, 0xb7, 0x92, 0xd8, 0xa8, 0x89, 0xa4, 0xc6, 0xc4, 0x70, 0x28,
	0x09, 0x1e, 0x4c, 0xbc, 0x01, 0x9a, 0x18, 0x15, 0x4a, 0x28, 0x5c, 0x4c, 0x0c, 0xa9, 0x74, 0xad,
	0x9b, 0xb4, 0xdd, 0x66, 0xba, 0x25, 0xfa, 0x2d, 0xfc, 0x0c, 0x7e, 0xd2, 0xb7, 0xdd, 0x6d, 0x79,
	0xf0, 0xf2, 0x0e, 0xef, 0xb4, 0xed, 0xfc, 0xfe, 0xcd, 0xec, 0x2c, 0xf4, 0x78, 0x4a, 0xd1, 0x17,
	0x1c, 0x9d, 0x14, 0xb9, 0xe0, 0xa4, 0x55, 0xfd, 0x3f, 0x1f, 0x87, 0x9c, 0x87, 0x11, 0x9d, 0xaa,
	0xfa, 0xcf, 0xfc, 0xd7, 0x34, 0xa0, 0xd9, 0x11, 0x59, 0x7a, 0xe6, 0xda, 0xbf, 0xa1, 0xe9, 0xf1,
	0x1c, 0x8f, 0x94, 0xd8, 0x60, 0x88, 0xbf, 0x29, 0xb5, 0x6a, 0xe3, 0xda, 0xdb, 0xde, 0x6c, 0xe4,
	0x9c, 0x4d, 0x35, 0xbe, 0x93, 0x18, 0x79, 0x09, 0x46, 0x9e, 0x51, 0xb4, 0xea, 0x92, 0xd3, 0x99,
	0xf5, 0x6e, 0x39, 0x7b, 0x59, 0x2d, 0x50, 0xe4, 0x3c, 0xb6, 0x1a, 0x77, 0xd1, 0xad, 0xac, 0xda,
	0x23, 0x30, 0x8a, 0x93, 0x3c, 0x01, 0x23, 0xf1, 0x63, 0x9d, 0xd3, 0xb6, 0x97, 0x60, 0x28, 0x2d,
	0x40, 0x9d, 0x05, 0xba, 0x46, 0xba, 0xf0, 0x38, 0xe2, 0x21, 0x4b, 0x54, 0x4c, 0x9b, 0x0c, 0xa1,
	0x8d, 0xd4, 0x8f, 0x0e, 0x4a, 0xd5, 0xa8, 0x18, 0x34, 0xf6, 0x59, 0x64, 0x19, 0xca, 0xe4, 0x05,
	0x34, 0xdd, 0x5c, 0xa4, 0xb9, 0x28, 0xb8, 0x9b, 0xc8, 0x67, 0xc9, 0x8e, 0xfe, 0x11, 0x65, 0xc2,
	0x0f, 0x78, 0xea, 0x51, 0x3c, 0x51, 0xf4, 0x84, 0x8f, 0x22, 0x4f, 0xd7, 0x5c, 0x30, 0x39, 0x6e,
	0x1f, 0xcc, 0x79, 0x10, 0x20, 0xcd, 0xb2, 0x32, 0x75, 0x00, 0xad, 0x4d, 0x71, 0x25, 0x47, 0x1e,
	0x95, 0xc1, 0xaf, 0xa1, 0x25, 0x5b, 0x3b, 0x49, 0x76, 0x26, 0x73, 0x1b, 0x72, 0xa6, 0xe1, 0xc5,
	0xad, 0x68, 0xc4, 0x7e, 0x03, 0xe4, 0xca, 0xfe, 0x13, 0x22, 0xc7, 0xc2, 0x3d, 0x96, 0xd6, 0x7e,
	0x58, 0xcd, 0xf9, 0x1e, 0x86, 0xa5, 0x62, 0x4b, 0x43, 0x96, 0x09, 0x8a, 0x34, 0x90, 0x57, 0x6e,
	0x96, 0x01, 0x8a, 0x75, 0xaf, 0xff, 0x17, 0xdd, 0xbe, 0xfc, 0xbc, 0x0a, 0x78, 0x80, 0xf4, 0xb2,
	0x09, 0x35, 0x90, 0xfd, 0x0c, 0xcc, 0x0a, 0xbb, 0xda, 0xc2, 0x64, 0x02, 0x70, 0xb1, 0xe5, 0x3e,
	0x74, 0x3e, 0xef, 0x17, 0xee, 0xee, 0xe0, 0x7d, 0x9b, 0x2f, 0xbf, 0x0e, 0x1e, 0x91, 0x0e, 0x98,
	0x4b, 0x77, 0xb5, 0x9a, 0xaf, 0x3f, 0x0e, 0x6a, 0x1f, 0xa6, 0x5a, 0x49, 0x5e, 0x39, 0xfa, 0x71,
	0x39, 0xd5, 0xe3, 0xaa, 0x72, 0xdd, 0x54, 0x30, 0x9e, 0x64, 0xd6, 0xff, 0x7f, 0x6a, 0x59, 0x8b,
	0xfe, 0xf7, 0x6e, 0xd5, 0x9a, 0xa6, 0x36, 0xd5, 0xf1, 0xee, 0x26, 0x00, 0x00, 0xff, 0xff, 0x7a,
	0x75, 0xaf, 0x52, 0xb8, 0x02, 0x00, 0x00,
}
