#!/bin/sh
# script/server: Launch the application and any extra required processes
#                locally.
set -eu
cd "$(dirname "$0")/.."

: "${RACK_ENV:="development"}"

# Race condition when starting up multiple containers
# So wait for mysql in docker composer
# https://github.com/docker/compose/issues/374
test -n "$DATABASE_HOST" &&
  while ! nc -w 1 "$DATABASE_HOST" "$DATABASE_PORT" 1>/dev/null 2>/dev/null
  do
    echo "Waiting for MySQL"
    sleep 1
  done

# ensure everything in the app is up to date.
script/update

test "$RACK_ENV" = "development" && {
    for dbname in pardot_global pardot_shard1 pardot_shard2
    do
        dump="db/vagrant-dev/${dbname}.sql"
        echo "==> Importing $dump into database $dbname"
        mysqladmin -h "$DATABASE_HOST" -P "$DATABASE_PORT" \
            create "$dbname" 2>/dev/null || true
        mysql -h "$DATABASE_HOST" -P "$DATABASE_PORT" "$dbname" < "$dump"
    done
}

rm -f tmp/pids/server.pid
export TERM=
exec bin/foreman start -p "${PORT-3000}"
