#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "===> Setting up DB..."
# reset database to a fresh state.
bin/rake db:reset

echo "==> App is now ready to go!"
