#!/bin/sh
# script/test: Run test suite for application. Optionallly pass in a path to an
#              individual test file to run a single test.
set -eu

cd "$(dirname "$0")/.."

: "${DEBUG:=""}"
[ -z "$DEBUG" ] || set -x

export RACK_ROOT=$(cd "$(dirname $0)"/.. && pwd)

if test "${RAILS_ENV:-""}" = "test"
then
    script/setup
    script/vagrant-dev-mysqlimport
else
    RACK_ENV="test"
    RAILS_ENV="test"
    export RACK_ENV RAILS_ENV

    script/update
fi

echo "===> Running tests..."

if [ -n "${1:-""}" ]; then
  bin/rake test "$1"
else
  bin/rake
fi
