#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating db..."
# run all database migrations to ensure everything is up to date.
bin/rake db:create db:migrate

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  # Only run in development environments
  echo "===> Adding development targets"
  bin/rake canoe:create_dev_targets
  echo "===> Adding repos"
  bin/rake canoe:create_repos
fi
