package main

import "github.com/sr/operator/generator"

var builderTemplate = generator.NewTemplate("builder-gen.go",
	`// Code generated by protoc-gen-operatord
package main

import (
	"github.com/sr/operator"
	"golang.org/x/net/context"
	"google.golang.org/grpc"

{{range $k, $v := .Imports}}
	{{$k}} "{{$v}}"
{{end}}
)

func invoker(ctx context.Context, conn *grpc.ClientConn, req *operator.Request) (bool, error) {
{{- range .Services}}
	{{- $pkg := .Package }}
	{{- $svc := .FullName }}
	if req.Call.Service == "{{lowerCase .Name}}" {
	{{- range .Methods }}
		if req.Call.Method == "{{lowerCase .Name}}" {
			client := {{$pkg}}.New{{$svc}}Client(conn)
			_, err := client.{{.Name}}(
				ctx,
				&{{$pkg}}.{{.Input}}{
					Request: req,
					{{- range .Arguments}}
					{{camelCase .Name}}: req.Call.Args["{{.Name}}"],
					{{- end}}
				},
			)
			if err != nil {
				return true, err
			}
			return true, nil
		}
	{{- end }}
	}
{{- end }}
	return false, nil
}
`)
