#!/usr/bin/env bash
set -eu

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"
cd "$dir"

: "${HUBOT_ALIAS:="!"}"
: "${HUBOT_NAME:="Parbot"}"

: "${HUBOT_HIPCHAT_XMPP_DOMAIN:="btf.hipchat.com"}"
: "${HUBOT_HIPCHAT_HOST:="hipchat.dev.pardot.com"}"
export HUBOT_HIPCHAT_XMPP_DOMAIN HUBOT_HIPCHAT_HOST

# checkout the README and add a secrets.sh file to connect to hipchat
test -f "$dir/script/secrets.sh" && source "$dir/script/secrets.sh"

exec bin/hubot --name "$HUBOT_NAME" --alias "$HUBOT_ALIAS" --disable-httpd "$@"
