// Code generated by protoc-gen-go.
// source: ping/ping.proto
// DO NOT EDIT!

/*
Package breadping is a generated protocol buffer package.

It is generated from these files:
	ping/ping.proto

It has these top-level messages:
	PingerConfig
	OtpRequest
	PingRequest
	WhoamiRequest
*/
package breadping

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingerConfig struct {
}

func (m *PingerConfig) Reset()                    { *m = PingerConfig{} }
func (m *PingerConfig) String() string            { return proto.CompactTextString(m) }
func (*PingerConfig) ProtoMessage()               {}
func (*PingerConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OtpRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *OtpRequest) Reset()                    { *m = OtpRequest{} }
func (m *OtpRequest) String() string            { return proto.CompactTextString(m) }
func (*OtpRequest) ProtoMessage()               {}
func (*OtpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OtpRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type PingRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Arg1    string            `protobuf:"bytes,2,opt,name=arg1" json:"arg1,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type WhoamiRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *WhoamiRequest) Reset()                    { *m = WhoamiRequest{} }
func (m *WhoamiRequest) String() string            { return proto.CompactTextString(m) }
func (*WhoamiRequest) ProtoMessage()               {}
func (*WhoamiRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WhoamiRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*PingerConfig)(nil), "ping.PingerConfig")
	proto.RegisterType((*OtpRequest)(nil), "ping.OtpRequest")
	proto.RegisterType((*PingRequest)(nil), "ping.PingRequest")
	proto.RegisterType((*WhoamiRequest)(nil), "ping.WhoamiRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Pinger service

type PingerClient interface {
	Otp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*operator.Response, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*operator.Response, error)
	Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*operator.Response, error)
}

type pingerClient struct {
	cc *grpc.ClientConn
}

func NewPingerClient(cc *grpc.ClientConn) PingerClient {
	return &pingerClient{cc}
}

func (c *pingerClient) Otp(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/ping.Pinger/Otp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/ping.Pinger/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/ping.Pinger/Whoami", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pinger service

type PingerServer interface {
	Otp(context.Context, *OtpRequest) (*operator.Response, error)
	Ping(context.Context, *PingRequest) (*operator.Response, error)
	Whoami(context.Context, *WhoamiRequest) (*operator.Response, error)
}

func RegisterPingerServer(s *grpc.Server, srv PingerServer) {
	s.RegisterService(&_Pinger_serviceDesc, srv)
}

func _Pinger_Otp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Otp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.Pinger/Otp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Otp(ctx, req.(*OtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.Pinger/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.Pinger/Whoami",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Whoami(ctx, req.(*WhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pinger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ping.Pinger",
	HandlerType: (*PingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Otp",
			Handler:    _Pinger_Otp_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Pinger_Ping_Handler,
		},
		{
			MethodName: "Whoami",
			Handler:    _Pinger_Whoami_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("ping/ping.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0xcc, 0x4b,
	0xd7, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x14, 0x5f, 0x7e,
	0x41, 0x6a, 0x51, 0x62, 0x49, 0x7e, 0x11, 0x44, 0x54, 0x89, 0x8f, 0x8b, 0x27, 0x20, 0x33, 0x2f,
	0x3d, 0xb5, 0xc8, 0x39, 0x3f, 0x2f, 0x2d, 0x33, 0x5d, 0xc9, 0x92, 0x8b, 0xcb, 0xbf, 0xa4, 0x20,
	0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x9b, 0x8b, 0xbd, 0x08, 0xc2, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd4, 0x83, 0xeb, 0x87, 0xaa, 0x09, 0x82, 0xa9, 0x50, 0xf2, 0xe3,
	0xe2, 0x06, 0x19, 0x45, 0x8e, 0x5e, 0x21, 0x21, 0x2e, 0x96, 0xc4, 0xa2, 0x74, 0x43, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc9, 0x86, 0x8b, 0x37, 0x3c, 0x23, 0x3f, 0x31, 0x37,
	0x93, 0x1c, 0x13, 0x8d, 0x16, 0x32, 0x72, 0xb1, 0x41, 0x7c, 0x26, 0xa4, 0xcd, 0xc5, 0xec, 0x5f,
	0x52, 0x20, 0x24, 0xa0, 0x07, 0x0e, 0x0d, 0x84, 0xf7, 0xa4, 0x84, 0x90, 0xf5, 0x17, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x0a, 0xe9, 0x72, 0xb1, 0x80, 0xb4, 0x09, 0x09, 0x42, 0x54, 0x23, 0xf9, 0x08,
	0xab, 0x72, 0x43, 0x2e, 0x36, 0x88, 0x23, 0x85, 0x84, 0x21, 0x1a, 0x50, 0x9c, 0x8c, 0x4d, 0x8b,
	0x14, 0xc7, 0xa4, 0x26, 0x49, 0x70, 0x64, 0x38, 0x71, 0x47, 0x71, 0x26, 0x15, 0xa5, 0x26, 0xa6,
	0x80, 0x38, 0x49, 0x6c, 0xe0, 0x08, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x0e, 0x36,
	0x40, 0xb9, 0x01, 0x00, 0x00,
}
