source "https://rubygems.org"
gem "byebug", group: [:development, :test]
gem "coffee-rails", "~> 4.0", group: [:development, :test]
gem "foreman", "0.78.0"
gem "jquery-rails"
gem "mysql2", "0.4.3"
gem "omniauth", "1.3.1"
gem "omniauth-ldap", "~>1.0"
gem "puma", "~>3.4"
gem "rails", "4.2.6"
gem "pardot-rubylib", path: "../rubylib"
gem "sass-rails", "~> 5.0"
gem "sql-parser", github: "janSF/sql-parser"
gem "turbolinks"
gem "uglifier", ">= 1.3.0", group: [:development, :test]
gem "will_paginate"
