source "https://artifactory.dev.pardot.com/artifactory/api/gems/pd-gem/"
gem "byebug", "~> 9.0", group: [:development, :test]
gem "coffee-rails", "~> 4.0", group: [:development, :test]
gem "foreman", "0.78.0"
gem "jquery-rails"
gem "mysql2", "0.4.4"
gem "omniauth", "1.3.1"
gem "omniauth-ldap", "~>1.0"
gem "pardot-rubylib", path: "vendor/cache/rubylib"
gem "pinglish", "~>0.2"
gem "puma", "~>3.4"
gem "rails", "5.0.0.1"
gem "sass-rails", "~> 5.0"
gem "sql-parser", git: "https://github.com/janSF/sql-parser"
gem "turbolinks"
gem "uglifier", ">= 1.3.0", group: [:development, :test]
gem "will_paginate"
