package main

import "github.com/sr/operator/generator"

var template = generator.NewTemplate("help.txt",
	`# Code generated by protoc-gen-operatorlitahelp
{{- range .Services}}
{{- if .Enabled}}
{{- $svc := .Name }}
{{- range .Methods }}
HAL9000: {{serviceName $svc}} {{methodName .Name}} {{range .Arguments}}{{.Name}}=value {{end}}- {{.Description}}
{{- end }}
{{- end }}
{{- end }}
`)
