package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CanoePhoneAuthenticationResponse canoe phone authentication response
// swagger:model canoePhoneAuthenticationResponse
type CanoePhoneAuthenticationResponse struct {

	// error
	Error bool `json:"error,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// user email
	UserEmail string `json:"user_email,omitempty"`
}

// Validate validates this canoe phone authentication response
func (m *CanoePhoneAuthenticationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
