FROM docker.dev.pardot.com/base/centos:7

ARG packer_version=0.12.3
ARG packer_checksum=d11c7ff78f546abaced4fcc7828f59ba1346e88276326d234b7afed32c9578fe

RUN yum install -y unzip && \
  yum clean all

RUN curl -Lo /tmp/packer.zip "https://releases.hashicorp.com/packer/0.12.3/packer_${packer_version}_linux_amd64.zip" && \
  echo "${packer_checksum}  /tmp/packer.zip" | sha256sum -c - && \
  cd /tmp && \
  unzip packer.zip && \
  mv packer /usr/bin && \
  rm /tmp/packer.zip
