#!/usr/bin/env bash
# script/server: Launch the application and any extra required processes
#                locally.
set -eu
cd "$(dirname "$0")/.."

: "${RACK_ENV:="development"}"
export RACK_ENV

# Race condition when starting up multiple containers
# So wait for mysql in docker composer
# https://github.com/docker/compose/issues/374
test -n "${DATABASE_HOST-localhost}" &&
  while ! nc -w 1 "${DATABASE_HOST-localhost}" "${DATABASE_PORT-3306}" 1>/dev/null 2>/dev/null
  do
    echo "Waiting for MySQL"
    sleep 1
  done

script/update
script/vagrant-dev-mysqlimport

rm -f tmp/pids/server.pid
export TERM=
exec bin/foreman start -p "${PORT-3000}"
