[#-- @ftlvariable name="repository" type="com.pardot.bread.bambooplugin.repository.GithubEnterpriseRepository" --]
[@s.checkbox labelKey='repository.githubenterprise.useSubmodules' name='repository.githubenterprise.useSubmodules' /]
[@s.textfield labelKey='repository.githubenterprise.commandTimeout' name='repository.githubenterprise.commandTimeout' /]
[@s.checkbox labelKey='repository.githubenterprise.verbose.logs' name='repository.githubenterprise.verbose.logs' /]
[@s.checkbox labelKey='repository.githubenterprise.fetch.whole.repository' name='repository.githubenterprise.fetch.whole.repository' /]
[@s.checkbox labelKey='repository.githubenterprise.lfs' name='repository.githubenterprise.lfs' /]
