package canoe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"git.dev.pardot.com/Pardot/bread/swagger/models"
)

// PhoneAuthenticationReader is a Reader for the PhoneAuthentication structure.
type PhoneAuthenticationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PhoneAuthenticationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPhoneAuthenticationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPhoneAuthenticationOK creates a PhoneAuthenticationOK with default headers values
func NewPhoneAuthenticationOK() *PhoneAuthenticationOK {
	return &PhoneAuthenticationOK{}
}

/*PhoneAuthenticationOK handles this case with default header values.

PhoneAuthenticationOK phone authentication o k
*/
type PhoneAuthenticationOK struct {
	Payload *models.CanoePhoneAuthenticationResponse
}

func (o *PhoneAuthenticationOK) Error() string {
	return fmt.Sprintf("[POST /api/grpc/phone_authentication][%d] phoneAuthenticationOK  %+v", 200, o.Payload)
}

func (o *PhoneAuthenticationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CanoePhoneAuthenticationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
