#!/usr/bin/env bash
# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "===> Setting up DB..."
bin/rake db:create db:migrate

echo "==> App is now ready to go!"
