#!/usr/bin/env bash
set -eu
cd "$(dirname "$0")/.."

vagrant_id="$(vagrant global-status | grep vagrant-dev | awk '{ print $1 }')"

for i in pardot_global pardot_shard1 pardot_shard2
do
    dest="db/vagrant-dev/$i.sql"
    echo "==> Dumping database $i from vagrant-dev to $dest"
    vagrant ssh "$vagrant_id" \
        -c "mysqldump -uroot -ppardot07 --databases $i" 2>/dev/null > "$dest"
done
