// Code generated by protoc-gen-go.
// source: bread.proto
// DO NOT EDIT!

/*
Package breadpb is a generated protocol buffer package.

It is generated from these files:
	bread.proto
	deploy.proto
	ping.proto
	repository.proto
	tickets.proto

It has these top-level messages:
	OperatorRequest
	OperatorMessage
	GithubEvent
	JIRAEvent
	HTTPRequest
	ServerStartupNotice
	ServiceStartupError
	ListTargetsRequest
	ListBuildsRequest
	TriggerRequest
	PingRequest
	SlowLorisRequest
	RepositoryConfig
	RepositoryWatchlist
	TicketRequest
*/
package breadpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import operator "github.com/sr/operator"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperatorRequest struct {
	Event   string            `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Request *operator.Request `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Message *OperatorMessage  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Error   string            `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *OperatorRequest) Reset()                    { *m = OperatorRequest{} }
func (m *OperatorRequest) String() string            { return proto.CompactTextString(m) }
func (*OperatorRequest) ProtoMessage()               {}
func (*OperatorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OperatorRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *OperatorRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *OperatorRequest) GetMessage() *OperatorMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *OperatorRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type OperatorMessage struct {
	Source *operator.Source `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Text   string           `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Html   string           `protobuf:"bytes,3,opt,name=html" json:"html,omitempty"`
}

func (m *OperatorMessage) Reset()                    { *m = OperatorMessage{} }
func (m *OperatorMessage) String() string            { return proto.CompactTextString(m) }
func (*OperatorMessage) ProtoMessage()               {}
func (*OperatorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OperatorMessage) GetSource() *operator.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *OperatorMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *OperatorMessage) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

type GithubEvent struct {
	Id        string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type      string         `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Payload   []byte         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Forwarded []*HTTPRequest `protobuf:"bytes,4,rep,name=forwarded" json:"forwarded,omitempty"`
}

func (m *GithubEvent) Reset()                    { *m = GithubEvent{} }
func (m *GithubEvent) String() string            { return proto.CompactTextString(m) }
func (*GithubEvent) ProtoMessage()               {}
func (*GithubEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GithubEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GithubEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GithubEvent) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GithubEvent) GetForwarded() []*HTTPRequest {
	if m != nil {
		return m.Forwarded
	}
	return nil
}

type JIRAEvent struct {
	Id        int32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type      string         `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	IssueKey  string         `protobuf:"bytes,3,opt,name=issue_key,json=issueKey" json:"issue_key,omitempty"`
	Forwarded []*HTTPRequest `protobuf:"bytes,4,rep,name=forwarded" json:"forwarded,omitempty"`
}

func (m *JIRAEvent) Reset()                    { *m = JIRAEvent{} }
func (m *JIRAEvent) String() string            { return proto.CompactTextString(m) }
func (*JIRAEvent) ProtoMessage()               {}
func (*JIRAEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JIRAEvent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JIRAEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JIRAEvent) GetIssueKey() string {
	if m != nil {
		return m.IssueKey
	}
	return ""
}

func (m *JIRAEvent) GetForwarded() []*HTTPRequest {
	if m != nil {
		return m.Forwarded
	}
	return nil
}

type HTTPRequest struct {
	Method     string                    `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Path       string                    `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Query      map[string]string         `protobuf:"bytes,3,rep,name=query" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusCode uint32                    `protobuf:"varint,7,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Duration   *google_protobuf.Duration `protobuf:"bytes,8,opt,name=duration" json:"duration,omitempty"`
	Error      string                    `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *HTTPRequest) Reset()                    { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()               {}
func (*HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HTTPRequest) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *HTTPRequest) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *HTTPRequest) GetDuration() *google_protobuf.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *HTTPRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ServerStartupNotice struct {
	Address  string   `protobuf:"bytes,1,opt,name=Address,json=address" json:"Address,omitempty"`
	Protocol string   `protobuf:"bytes,2,opt,name=Protocol,json=protocol" json:"Protocol,omitempty"`
	Services []string `protobuf:"bytes,3,rep,name=services" json:"services,omitempty"`
	Hal9000  string   `protobuf:"bytes,4,opt,name=Hal9000,json=hal9000" json:"Hal9000,omitempty"`
}

func (m *ServerStartupNotice) Reset()                    { *m = ServerStartupNotice{} }
func (m *ServerStartupNotice) String() string            { return proto.CompactTextString(m) }
func (*ServerStartupNotice) ProtoMessage()               {}
func (*ServerStartupNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerStartupNotice) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServerStartupNotice) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ServerStartupNotice) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *ServerStartupNotice) GetHal9000() string {
	if m != nil {
		return m.Hal9000
	}
	return ""
}

type ServiceStartupError struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ServiceStartupError) Reset()                    { *m = ServiceStartupError{} }
func (m *ServiceStartupError) String() string            { return proto.CompactTextString(m) }
func (*ServiceStartupError) ProtoMessage()               {}
func (*ServiceStartupError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceStartupError) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceStartupError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*OperatorRequest)(nil), "bread.OperatorRequest")
	proto.RegisterType((*OperatorMessage)(nil), "bread.OperatorMessage")
	proto.RegisterType((*GithubEvent)(nil), "bread.GithubEvent")
	proto.RegisterType((*JIRAEvent)(nil), "bread.JIRAEvent")
	proto.RegisterType((*HTTPRequest)(nil), "bread.HTTPRequest")
	proto.RegisterType((*ServerStartupNotice)(nil), "bread.ServerStartupNotice")
	proto.RegisterType((*ServiceStartupError)(nil), "bread.ServiceStartupError")
}

func init() { proto.RegisterFile("bread.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0xa6, 0x8e, 0xc7, 0x7c, 0x94, 0x05, 0x55, 0x26, 0x08, 0x88, 0x2c, 0x21, 0x45,
	0x42, 0x72, 0xa2, 0x56, 0x48, 0x85, 0x5b, 0x81, 0x88, 0x02, 0x02, 0xca, 0xb6, 0x27, 0x2e, 0xd5,
	0xc6, 0x9e, 0x26, 0x16, 0x4e, 0xd7, 0xdd, 0x5d, 0x07, 0x7c, 0x00, 0x89, 0x3f, 0xc1, 0x89, 0x1f,
	0x8b, 0xf6, 0xc3, 0x71, 0x04, 0xe2, 0xc2, 0x6d, 0xdf, 0xcc, 0x9b, 0x99, 0x37, 0x6f, 0x07, 0xa2,
	0x99, 0x40, 0x96, 0xa7, 0x95, 0xe0, 0x8a, 0x93, 0x9e, 0x01, 0x83, 0x07, 0x73, 0xce, 0xe7, 0x25,
	0x8e, 0x4d, 0x70, 0x56, 0x5f, 0x8c, 0xf3, 0x5a, 0x30, 0x55, 0xf0, 0x4b, 0x4b, 0x1b, 0x3c, 0x9a,
	0x17, 0x6a, 0x51, 0xcf, 0xd2, 0x8c, 0x2f, 0xc7, 0x52, 0x8c, 0x79, 0x85, 0x82, 0x29, 0xde, 0x3d,
	0x2c, 0x2d, 0xf9, 0xe5, 0xc1, 0xcd, 0x0f, 0x2e, 0x44, 0xf1, 0xaa, 0x46, 0xa9, 0xc8, 0x1d, 0xe8,
	0xe1, 0x0a, 0x2f, 0x55, 0xec, 0x0d, 0xbd, 0x51, 0x48, 0x2d, 0x20, 0x8f, 0x21, 0x10, 0x96, 0x10,
	0xfb, 0x43, 0x6f, 0x14, 0xed, 0xdf, 0x4a, 0xd7, 0xbd, 0x5c, 0x25, 0x6d, 0x19, 0x64, 0x02, 0xc1,
	0x12, 0xa5, 0x64, 0x73, 0x8c, 0xb7, 0x0c, 0x79, 0x2f, 0xb5, 0x3b, 0xb4, 0xb3, 0xde, 0xd9, 0x2c,
	0x6d, 0x69, 0x66, 0xa8, 0x10, 0x5c, 0xc4, 0xdb, 0x6e, 0xa8, 0x06, 0x49, 0xd6, 0xa9, 0x73, 0x15,
	0x64, 0x04, 0x3b, 0x92, 0xd7, 0x22, 0x43, 0x23, 0x2f, 0xda, 0xdf, 0xed, 0x64, 0x9c, 0x9a, 0x38,
	0x75, 0x79, 0x42, 0x60, 0x5b, 0xe1, 0x57, 0x2b, 0x37, 0xa4, 0xe6, 0xad, 0x63, 0x0b, 0xb5, 0x2c,
	0x8d, 0xaa, 0x90, 0x9a, 0x77, 0xf2, 0x0d, 0xa2, 0x57, 0xc6, 0xac, 0xa9, 0x59, 0xf4, 0x06, 0xf8,
	0x45, 0xee, 0x76, 0xf7, 0x8b, 0xdc, 0xb4, 0x69, 0x2a, 0x5c, 0xb7, 0x69, 0x2a, 0x24, 0x31, 0x04,
	0x15, 0x6b, 0x4a, 0xce, 0x72, 0xd3, 0xe9, 0x1a, 0x6d, 0x21, 0x99, 0x40, 0x78, 0xc1, 0xc5, 0x17,
	0x26, 0x72, 0xcc, 0xe3, 0xed, 0xe1, 0xd6, 0x28, 0xda, 0x27, 0x6e, 0xf7, 0xe3, 0xb3, 0xb3, 0x93,
	0xd6, 0xa9, 0x8e, 0x94, 0x7c, 0x87, 0xf0, 0xcd, 0x6b, 0x7a, 0xf4, 0xe7, 0xf0, 0xde, 0x3f, 0x87,
	0xdf, 0x83, 0xb0, 0x90, 0xb2, 0xc6, 0xf3, 0xcf, 0xd8, 0xb8, 0x45, 0xfa, 0x26, 0xf0, 0x16, 0x9b,
	0xff, 0x98, 0xff, 0xd3, 0x87, 0x68, 0x23, 0x45, 0xf6, 0x60, 0x67, 0x89, 0x6a, 0xc1, 0x5b, 0x0f,
	0x1c, 0xd2, 0x52, 0x2a, 0xa6, 0x16, 0xad, 0x14, 0xfd, 0x26, 0x07, 0xd0, 0xbb, 0xaa, 0x51, 0x68,
	0x19, 0x7a, 0xd2, 0xfd, 0xbf, 0x27, 0xa5, 0x1f, 0x75, 0x7e, 0x7a, 0xa9, 0x44, 0x43, 0x2d, 0x97,
	0x3c, 0x84, 0x48, 0x2a, 0xa6, 0x6a, 0x79, 0x9e, 0xf1, 0x1c, 0xe3, 0x60, 0xe8, 0x8d, 0xae, 0x53,
	0xb0, 0xa1, 0x17, 0x3c, 0x47, 0xf2, 0x04, 0xfa, 0xed, 0x35, 0xc7, 0x7d, 0xf3, 0xc9, 0x77, 0x53,
	0x7b, 0xee, 0x69, 0x7b, 0xee, 0xe9, 0x4b, 0x47, 0xa0, 0x6b, 0x6a, 0x77, 0x42, 0xe1, 0xc6, 0x09,
	0x0d, 0x0e, 0x01, 0x3a, 0x09, 0x64, 0x17, 0xb6, 0xb4, 0x6b, 0x76, 0x33, 0xfd, 0xd4, 0x55, 0x2b,
	0x56, 0xd6, 0xad, 0xc5, 0x16, 0x3c, 0xf3, 0x0f, 0xbd, 0xe4, 0x87, 0x07, 0xb7, 0x4f, 0x51, 0xac,
	0x50, 0x9c, 0x2a, 0x26, 0x54, 0x5d, 0xbd, 0xe7, 0xaa, 0xc8, 0xcc, 0xe7, 0x1f, 0xe5, 0xb9, 0x40,
	0x29, 0x5d, 0x9f, 0x80, 0x59, 0x48, 0x06, 0xd0, 0x3f, 0xd1, 0x02, 0x33, 0x5e, 0xba, 0x76, 0xfd,
	0xca, 0x61, 0x9d, 0x93, 0x28, 0x56, 0x45, 0x86, 0xd2, 0xb8, 0x15, 0xd2, 0x35, 0xd6, 0x1d, 0x8f,
	0x59, 0xf9, 0x74, 0x32, 0x99, 0xb8, 0xf3, 0x0f, 0x16, 0x16, 0x26, 0x53, 0x2b, 0xa1, 0xc8, 0xd0,
	0x69, 0x98, 0xea, 0xa5, 0x74, 0x81, 0x2b, 0x6e, 0x25, 0x38, 0xd8, 0x99, 0xe0, 0x6f, 0x98, 0xf0,
	0x3c, 0xfc, 0x14, 0x98, 0x9f, 0xa9, 0x66, 0xb3, 0x1d, 0xa3, 0xe8, 0xe0, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x76, 0xcd, 0x15, 0x63, 0x55, 0x04, 0x00, 0x00,
}
