// Code generated by protoc-gen-go.
// source: tickets.proto
// DO NOT EDIT!

package breadpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import operator "github.com/sr/operator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MyIssuesRequest struct {
	Request *operator.Request `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *MyIssuesRequest) Reset()                    { *m = MyIssuesRequest{} }
func (m *MyIssuesRequest) String() string            { return proto.CompactTextString(m) }
func (*MyIssuesRequest) ProtoMessage()               {}
func (*MyIssuesRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *MyIssuesRequest) GetRequest() *operator.Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*MyIssuesRequest)(nil), "bread.MyIssuesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tickets service

type TicketsClient interface {
	// List in-progress issues assigned to the current user
	Mine(ctx context.Context, in *MyIssuesRequest, opts ...grpc.CallOption) (*operator.Response, error)
}

type ticketsClient struct {
	cc *grpc.ClientConn
}

func NewTicketsClient(cc *grpc.ClientConn) TicketsClient {
	return &ticketsClient{cc}
}

func (c *ticketsClient) Mine(ctx context.Context, in *MyIssuesRequest, opts ...grpc.CallOption) (*operator.Response, error) {
	out := new(operator.Response)
	err := grpc.Invoke(ctx, "/bread.Tickets/Mine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tickets service

type TicketsServer interface {
	// List in-progress issues assigned to the current user
	Mine(context.Context, *MyIssuesRequest) (*operator.Response, error)
}

func RegisterTicketsServer(s *grpc.Server, srv TicketsServer) {
	s.RegisterService(&_Tickets_serviceDesc, srv)
}

func _Tickets_Mine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketsServer).Mine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bread.Tickets/Mine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketsServer).Mine(ctx, req.(*MyIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tickets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bread.Tickets",
	HandlerType: (*TicketsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mine",
			Handler:    _Tickets_Mine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tickets.proto",
}

func init() { proto.RegisterFile("tickets.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc9, 0x4c, 0xce,
	0x4e, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2a, 0x4a, 0x4d, 0x4c,
	0x91, 0x52, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x2e, 0xd2,
	0xcf, 0x2f, 0x48, 0x2d, 0x4a, 0x2c, 0xc9, 0x47, 0x30, 0x20, 0xaa, 0x95, 0xec, 0xb8, 0xf8, 0x7d,
	0x2b, 0x3d, 0x8b, 0x8b, 0x4b, 0x53, 0x8b, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xb4,
	0xb9, 0xd8, 0x8b, 0x20, 0x4c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x41, 0x3d, 0xb8, 0x26,
	0xa8, 0x9a, 0x20, 0x98, 0x0a, 0x23, 0x5b, 0x2e, 0xf6, 0x10, 0x88, 0xf5, 0x42, 0x46, 0x5c, 0x2c,
	0xbe, 0x99, 0x79, 0xa9, 0x42, 0x62, 0x7a, 0x60, 0x17, 0xe8, 0xa1, 0x99, 0x2b, 0x25, 0x84, 0x6c,
	0x4c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x13, 0x67, 0x14, 0x3b, 0x58, 0x71, 0x41, 0x52, 0x12,
	0x1b, 0xd8, 0x41, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x43, 0x31, 0x36, 0xcf, 0x00,
	0x00, 0x00,
}
