// Code generated by protoc-gen-go.
// source: operator/operator.proto
// DO NOT EDIT!

/*
Package operator is a generated protocol buffer package.

It is generated from these files:
	operator/operator.proto

It has these top-level messages:
	Output
	ServerStartupNotice
	ServerStartupError
	ServiceStartupError
	Service
*/
package operator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Output struct {
	PlainText string `protobuf:"bytes,1,opt,name=PlainText" json:"PlainText,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServerStartupNotice struct {
	Address  string     `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
	Protocol string     `protobuf:"bytes,2,opt,name=Protocol" json:"Protocol,omitempty"`
	Services []*Service `protobuf:"bytes,3,rep,name=services" json:"services,omitempty"`
}

func (m *ServerStartupNotice) Reset()                    { *m = ServerStartupNotice{} }
func (m *ServerStartupNotice) String() string            { return proto.CompactTextString(m) }
func (*ServerStartupNotice) ProtoMessage()               {}
func (*ServerStartupNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerStartupNotice) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServerStartupError struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ServerStartupError) Reset()                    { *m = ServerStartupError{} }
func (m *ServerStartupError) String() string            { return proto.CompactTextString(m) }
func (*ServerStartupError) ProtoMessage()               {}
func (*ServerStartupError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ServiceStartupError struct {
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ServiceStartupError) Reset()                    { *m = ServiceStartupError{} }
func (m *ServiceStartupError) String() string            { return proto.CompactTextString(m) }
func (*ServiceStartupError) ProtoMessage()               {}
func (*ServiceStartupError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServiceStartupError) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type Service struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

var E_Name = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51234,
	Name:          "operator.name",
	Tag:           "bytes,51234,opt,name=name",
}

func init() {
	proto.RegisterType((*Output)(nil), "operator.Output")
	proto.RegisterType((*ServerStartupNotice)(nil), "operator.ServerStartupNotice")
	proto.RegisterType((*ServerStartupError)(nil), "operator.ServerStartupError")
	proto.RegisterType((*ServiceStartupError)(nil), "operator.ServiceStartupError")
	proto.RegisterType((*Service)(nil), "operator.Service")
	proto.RegisterExtension(E_Name)
}

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x55, 0x82, 0x9a, 0xf4, 0x40, 0x82, 0x9a, 0xa1, 0x11, 0x0c, 0x44, 0x46, 0x48, 0x9d,
	0x12, 0x09, 0x36, 0x36, 0x06, 0x16, 0x06, 0x5a, 0x29, 0xac, 0x0c, 0x6e, 0x62, 0xa2, 0x48, 0x69,
	0xce, 0x3a, 0x3b, 0x88, 0xc7, 0xe0, 0x19, 0x78, 0x52, 0x12, 0x3b, 0xae, 0x88, 0xd4, 0xcd, 0xbe,
	0xfb, 0xee, 0xbb, 0x5f, 0x07, 0x2b, 0x54, 0x92, 0x84, 0x41, 0xca, 0xfc, 0x23, 0x55, 0x84, 0x06,
	0x59, 0xe4, 0xff, 0xd7, 0x49, 0x85, 0x58, 0x35, 0x32, 0xb3, 0xf5, 0x5d, 0xf7, 0x99, 0x95, 0x52,
	0x17, 0x54, 0xab, 0x03, 0xcb, 0x6f, 0x60, 0xbe, 0xe9, 0x8c, 0xea, 0x0c, 0x5b, 0xc2, 0x62, 0xdb,
	0x88, 0xba, 0x7d, 0x97, 0xdf, 0x26, 0x9e, 0x25, 0xb3, 0xf5, 0x82, 0x7f, 0xc0, 0x55, 0x2e, 0xe9,
	0x4b, 0x52, 0x6e, 0x04, 0x99, 0x4e, 0xbd, 0xa1, 0xa9, 0x0b, 0xc9, 0x2e, 0x20, 0x7c, 0x2e, 0x4b,
	0x92, 0x5a, 0x3b, 0x8e, 0x5d, 0x42, 0xb4, 0x1d, 0x6c, 0x05, 0x36, 0xf1, 0x89, 0xad, 0xdc, 0x41,
	0xa4, 0xfb, 0xc9, 0x9e, 0xd6, 0x71, 0x90, 0x04, 0xeb, 0xb3, 0x87, 0x65, 0x7a, 0x48, 0x99, 0xbb,
	0x0e, 0xbf, 0x07, 0x36, 0xd1, 0xbf, 0x10, 0x21, 0x0d, 0xf6, 0x7d, 0xaf, 0x16, 0x95, 0x1c, 0x53,
	0xbc, 0xba, 0x14, 0xfd, 0xc4, 0x84, 0xe3, 0x10, 0x8e, 0x2b, 0x2c, 0x77, 0x6c, 0xc3, 0x7f, 0x97,
	0xcd, 0xc5, 0x57, 0x10, 0xfa, 0xde, 0x39, 0x9c, 0xb6, 0x62, 0x3f, 0x2e, 0x79, 0xca, 0xdc, 0x8f,
	0xdd, 0xa6, 0xee, 0x64, 0xa9, 0x3f, 0x99, 0x77, 0x6d, 0x94, 0xa9, 0xb1, 0xd5, 0xf1, 0xef, 0x4f,
	0x30, 0x0c, 0xec, 0xe6, 0x16, 0x78, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x37, 0xc9, 0x3e,
	0x86, 0x01, 0x00, 0x00,
}
