#!/bin/bash -e

MACHINE="rpms-el6"
BUILD_DIRECTORY="/home/vagrant/rpmbuild"

if [ $# -lt 1 ]; then
  echo "$0 <package> <package...>"
  exit 1
fi

set +e
vagrant up "$MACHINE"
set -e

for package in "$@"; do
  set -x
  vagrant ssh "$MACHINE" -- "sudo env BUILD_DIRECTORY=$BUILD_DIRECTORY $BUILD_DIRECTORY/script/local-build ${package}"
  set +x
done
