#!/bin/bash -e

MACHINE="${MACHINE:-el6}"
BUILD_DIRECTORY="/home/vagrant/rpmbuild"

if [ $# -lt 1 ]; then
  echo "$0 -n <package> <package...>"
  echo
  echo "-n: Do not run spectool. Sources must be downloaded manually and placed in SOURCES/"
  exit 1
fi

set +e
vagrant up "$MACHINE"
set -e

set -x
vagrant ssh "$MACHINE" -- "env BUILD_DIRECTORY=$BUILD_DIRECTORY $BUILD_DIRECTORY/script/local-build $*"
set +x
