#!/bin/bash -e

if [ $# -lt 1 ]; then
  echo "$0 [-f] [-n] <package> <package...>"
  echo
  echo "-f: Forces spectool to redownload sources"
  echo "-n: Do not run spectool. Sources must be downloaded manually and placed in SOURCES/"
  exit 1
fi

SPECOPTS=""
NOSPECTOOL=0
while getopts nf opt; do
  case "$opt" in
    n)
      NOSPECTOOL=1
      ;;
    f)
      SPECOPTS+="-f "
      ;;
    esac
done
shift $((OPTIND-1))

REDHAT_RELEASE=$(awk '{ print $3 }' /etc/redhat-release | cut -d. -f1)

set -x

if [ "$REDHAT_RELEASE" -le 5 ]; then
  echo "%_topdir ${BUILD_DIRECTORY}" > ~/.rpmmacros
  echo "%dist .el${REDHAT_RELEASE}" >> ~/.rpmmacros
fi

for package in "$@"; do
  if [ -n "$BUILD_DIRECTORY" ]; then
    cd "$BUILD_DIRECTORY"
  fi

  rpmlint SPECS/${package}.spec || exit 1

  # yum-builddep doesn't support passing a spec file on CentOS 5
  if [ "$REDHAT_RELEASE" -ge 6 ]; then
    sudo yum-builddep -y SPECS/${package}.spec;
  else
    # Do our best to pull out the dependencies
    egrep '^BuildRequires:' SPECS/${package}.spec |
      awk '{ print $2 }' |
      xargs sudo yum install -y
  fi

  [ "$NOSPECTOOL" -eq 1 ] || spectool $SPECOPTS -C SOURCES/ -g SPECS/${package}.spec;
  rpmbuild -ba SPECS/${package}.spec
done
