// Code generated by protoc-gen-operatord
package main

import (
	"time"

	"github.com/sr/operator"
	"golang.org/x/net/context"

	servicepkg "github.com/sr/operator/chatoops/services/gcloud"
)

type instrumentedgcloudGcloudService struct {
	instrumenter operator.Instrumenter
	server       servicepkg.GcloudServiceServer
}

// CreateDevInstance instruments the GcloudService.CreateDevInstance method.
func (a *instrumentedgcloudGcloudService) CreateDevInstance(
	ctx context.Context,
	request *servicepkg.CreateDevInstanceRequest,
) (response *servicepkg.CreateDevInstanceResponse, err error) {
	defer func(start time.Time) {
		a.instrumenter.Instrument(
			operator.NewRequest(
				request.Source,
				"gcloud",
				"CreateDevInstance",
				"CreateDevInstanceRequest",
				"CreateDevInstanceResponse",
				err,
				start,
			),
		)
	}(time.Now())
	return a.server.CreateDevInstance(ctx, request)
}

// ListInstances instruments the GcloudService.ListInstances method.
func (a *instrumentedgcloudGcloudService) ListInstances(
	ctx context.Context,
	request *servicepkg.ListInstancesRequest,
) (response *servicepkg.ListInstancesResponse, err error) {
	defer func(start time.Time) {
		a.instrumenter.Instrument(
			operator.NewRequest(
				request.Source,
				"gcloud",
				"ListInstances",
				"ListInstancesRequest",
				"ListInstancesResponse",
				err,
				start,
			),
		)
	}(time.Now())
	return a.server.ListInstances(ctx, request)
}

// Stop instruments the GcloudService.Stop method.
func (a *instrumentedgcloudGcloudService) Stop(
	ctx context.Context,
	request *servicepkg.StopRequest,
) (response *servicepkg.StopResponse, err error) {
	defer func(start time.Time) {
		a.instrumenter.Instrument(
			operator.NewRequest(
				request.Source,
				"gcloud",
				"Stop",
				"StopRequest",
				"StopResponse",
				err,
				start,
			),
		)
	}(time.Now())
	return a.server.Stop(ctx, request)
}
