// Code generated by protoc-gen-operatord
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/sr/operator"
	"google.golang.org/grpc"
)

const defaultListenAddr = "localhost:3000"

type noopAuthorizer struct{}

func (a noopAuthorizer) Authorize(*operator.Source) error {
	return nil
}

func run() error {
	config := &operator.Config{}
	flag.StringVar(&config.Address, "listen-addr", defaultListenAddr, "Listen address of the operator server")
	if config.Address == "" {
		return fmt.Errorf("required -listen-addr flag is missing.")
	}
	flag.Parse()
	server := grpc.NewServer()
	logger := operator.NewLogger()
	instrumenter := operator.NewInstrumenter(logger)
	registerServices(server, logger, instrumenter, noopAuthorizer{})
	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "operatord: %s\n", err)
		os.Exit(1)
	}
}
